#!/usr/bin/env python3
"""Build the cutdown's own build dir (cut/) from cut_plan.json, so every gate runs on it exactly as on the master:
  cut/words_ctc.json   the master's forced-aligned words re-timed through the AUDIO windows (a word in a J-cut lead
                       starts its caption at the seam, not under the previous range's muted graphic)
  cut/cut_timeline.json + cut/beats.py   the cutdown's beats / overlays / flashes in cut frames
  cut/crop.json        the master crop per cut frame, with talk-to-talk seams FLIPPED (FAR<->NEAR, hair-anchored y0)
  cut/edl_picture.json his picture segments in cut frames (the watch pass and the landing check read it)
  cut/his_mix.wav      HIS mix, cut at the same audio windows with 4 ms raised-cosine joins (it has no bed to rebuild:
                       30-120 Hz sits +4.9 dB in his gaps, a bed reads ~+12) -- the reference for the cutdown's gate
then renders the caption states (cut/cap, cut/captions.mov) with the same captions.py."""
import json, os, shutil, subprocess, sys, wave, numpy as np
sys.path.insert(0, '.')
import beats as B
FF = "/Users/danielrose/Documents/Claude/Projects/Abs By AI/Media/video_edit/bin/ffmpeg"
FPS = 30000/1001
P = json.load(open('cut_plan.json')); NC = P[-1]['c1']
os.makedirs('cut/logs', exist_ok=True)
def m2c(n):
    for p in P:
        if p['p0'] <= n < p['p1']: return p['c0'] + (n - p['p0'])
    return None
def t2c(t):
    n = t*FPS
    for p in P:
        if p['a0'] <= n < p['a1']: return t + (p['c0'] - p['p0'])/FPS, p
    return None, None
# ---- words ----------------------------------------------------------------------------------------------------------
out = []
for w in json.load(open('words_ctc.json')):
    s, p = t2c(float(w['start'])); e, q = t2c(float(w['end']) - 1e-3)
    if s is None or e is None or p is not q: continue
    if s < p['c0']/FPS: s = p['c0']/FPS + 0.06              # J-cut lead: just past the seam (the mute margin is 50 ms)
    out.append(dict(word=w['word'], start=round(s, 4), end=round(max(e + 1e-3, s + 0.04), 4), score=w.get('score', 0)))
json.dump(out, open('cut/words_ctc.json', 'w'))
# ---- timeline -------------------------------------------------------------------------------------------------------
tl, ov = B.timeline()
beats, ovs = [], []
for p in P:
    for b in tl:
        a, z = max(p['p0'], b['n0']), min(p['p1'], b['n1'])
        if a < z: beats.append(dict({k: v for k, v in b.items() if k not in ('t0', 't1', 'n0', 'n1')}, kind=b['kind'], n0=m2c(a), n1=m2c(z - 1) + 1, m0=a, m1=z))
    for o in ov:
        a, z = max(p['p0'], o['n0']), min(p['p1'], o['n1'])
        # a text overlay whose START lies in dropped material would print a sentence the cutdown never says
        if a < z and p['p0'] <= o['n0'] < p['p1']:
            ovs.append(dict({k: v for k, v in o.items() if k not in ('t0', 't1', 'n0', 'n1')}, kind=o['kind'], n0=m2c(a), n1=m2c(z - 1) + 1))
flashes = [m2c(n) for n in B.FLASHES if m2c(n) is not None]
json.dump(dict(NTOT=NC, beats=beats, overlays=ovs, flashes=flashes, seams=[p['c0'] for p in P[1:]]),
          open('cut/cut_timeline.json', 'w'), indent=1)
open('cut/beats.py', 'w').write('''"""The CUTDOWN's beat sheet in cut frames, generated by zcut_build.py from cut_plan.json (never edit by hand)."""
import json, os
_D = os.path.dirname(os.path.abspath(__file__))
FPS = 30000/1001
_T = json.load(open(os.path.join(_D, 'cut_timeline.json')))
NTOT = _T['NTOT']; DUR = NTOT / FPS
FLASHES = _T['flashes']; FLASH_K = 0.78
SEAMS = [s / FPS for s in _T['seams']]
NO_CAPS_KINDS = {'why', 'title', 'lock', 'app', 'fatdan'}
NO_CAPS_BODIES = {'note', 'bullets', 'phone'}
NO_CAPS_OVERLAYS = {'lt', 'chip', 'pill'}
def timeline():
    tl = [dict(b, t0=b['n0']/FPS, t1=b['n1']/FPS) for b in _T['beats']]
    ov = [dict(o, t0=o['n0']/FPS, t1=o['n1']/FPS) for o in _T['overlays']]
    return tl, ov
def muted_ranges():
    tl, ov = timeline()
    return [(b['t0'], b['t1']) for b in tl if b['kind'] in NO_CAPS_KINDS or (b['kind'] == 'window' and b.get('body') in NO_CAPS_BODIES)] + \\
           [(o['t0'], o['t1']) for o in ov if o['kind'] in NO_CAPS_OVERLAYS]
_Z = None
def push_at(t):
    global _Z
    if _Z is None: _Z = json.load(open(os.path.join(_D, 'crop.json')))['zoom_per_frame']
    n = int(t*FPS)
    return _Z[n] if 0 <= n < len(_Z) else 1.0
''')
# ---- crop, with flips at talk-to-talk seams -------------------------------------------------------------------------
C = json.load(open('crop.json')); CR = {int(k): v for k, v in C['frames'].items()}; H = C['holds']
HF, HN = C['H_FAR'], C['H_NEAR']
def hold_of(n): return next((h for h in H if h['n0'] <= n < h['n1']), None)
cc, zoom, holds_c = {}, [1.0]*NC, []
prev_lvl = None      # the level the previous range ENDS on (after its own flip); None when it ends off the talking head
for p in P:
    # Flip the incoming hold only when the seam would otherwise join two holds of the SAME level (a naked jump cut).
    # If the master's levels already differ across the seam it is a zoom cut as it stands -- an unconditional flip put
    # a drifting hold at NEAR and walked Dan to -132 px for 1.0 s (independent audit, 2026-09-10).
    f0 = hold_of(p['p0'])
    first = f0 if (p.get('flip') and f0 is not None and f0['level'] == prev_lvl) else None
    print(f"range {p['p0']}-{p['p1']}: {'seam flip APPLIED' if first is not None else 'talk seam, levels already differ' if p.get('flip') else 'no talk seam'}")
    last = hold_of(p['p1'] - 1)
    prev_lvl = None if last is None else (('NEAR' if last['level'] == 'FAR' else 'FAR') if (first is not None and last is first) else last['level'])
    for n in range(p['p0'], p['p1']):
        if n not in CR: continue
        x0, y0, w, h = CR[n]
        hh = hold_of(n)
        if first is not None and hh is first:
            cx = x0 + w/2
            H2 = HN if hh['level'] == 'FAR' else HF
            y0 = float(np.clip(hh['hmin'] - 0.04*H2, 0, 1080 - H2)); w = H2*9/16; h = H2
            x0 = float(np.clip(cx - w/2, 0, 1920 - w))
        cc[m2c(n)] = [round(x0, 2), round(y0, 2), round(w, 2), round(h, 2)]
        zoom[m2c(n)] = round(HF/h, 4)
    for hh in H:
        a, z = max(p['p0'], hh['n0']), min(p['p1'], hh['n1'])
        if a < z:
            lvl = hh['level'] if not (first is not None and hh is first) else ('NEAR' if hh['level'] == 'FAR' else 'FAR')
            n0c = m2c(a); holds_c.append(dict(n0=n0c, n1=m2c(z-1)+1, level=lvl, hmin=hh['hmin'], y0=cc[n0c][1]))
json.dump(dict(frames={str(k): v for k, v in cc.items()}, holds=holds_c, zoom_per_frame=zoom, H_FAR=HF, H_NEAR=HN),
          open('cut/crop.json', 'w'))
E = json.load(open('edl_picture.json')); ec = []
for p in P:
    for s in E:
        a, z = max(p['p0'], s['n0']), min(p['p1'], s['n1'])
        if a < z: ec.append(dict(n0=m2c(a), n1=m2c(z-1)+1, off=s['off'], src_in=s['src_in'] + (a - s['n0'])/FPS))
json.dump(ec, open('cut/edl_picture.json', 'w'))
# ---- his mix at the same audio windows ------------------------------------------------------------------------------
w = wave.open('his_mix.wav'); sr = w.getframerate(); x = np.frombuffer(w.readframes(w.getnframes()), np.int16).reshape(-1, 2).astype(np.float32)
F = int(0.004*sr); ramp = 0.5 - 0.5*np.cos(np.linspace(0, np.pi, F))[:, None]
parts = []
for p in P:
    a, z = round(p['a0']/FPS*sr), round(p['a1']/FPS*sr)
    seg = x[a:z].copy()
    if p is not P[0]: seg[:F] *= ramp
    if p is not P[-1]: seg[-F:] *= ramp[::-1]
    parts.append(seg)
y = np.concatenate(parts); want = round(NC/FPS*sr)
y = y[:want] if len(y) >= want else np.pad(y, ((0, want - len(y)), (0, 0)))
o = wave.open('cut/his_mix.wav', 'wb'); o.setnchannels(2); o.setsampwidth(2); o.setframerate(sr)
o.writeframes(np.clip(y, -32768, 32767).astype(np.int16).tobytes()); o.close()
# ---- gate inputs + captions -----------------------------------------------------------------------------------------
for f in ('captions.py', 'g5.py', 'centering.py', 'watch.py', 'landing_check.py'):
    shutil.copyfile(f, f'cut/{f}')
if not os.path.exists('cut/rc'): os.symlink(os.path.abspath('rc'), 'cut/rc')
q = json.load(open('qc.json')); q['target_seconds'] = round(NC/FPS, 6); json.dump(q, open('cut/qc.json', 'w'), indent=1)
subprocess.run(['python3', 'captions.py'], cwd='cut', check=True)
print(f'cut/: {NC} frames ({NC/FPS:.2f}s), {len(out)} words, {len(beats)} beats, {len(ovs)} overlays, flashes {flashes}')
