#!/usr/bin/env python3
"""Generate the CUTDOWN's own build modules in `cut/`, so its gates measure the cutdown.

⚠ WHY THIS EXISTS (skill lesson A6.18). Run from the parent directory, `qc.py` imports the
MASTER's `beats.py` and `centering.py` — so check 17 "passed" a cutdown against the master's
timeline, and checks that need the beat sheet either failed to import or graded the wrong
file. A green row that measured the wrong file is worse than a red one.

Everything here is DERIVED from `cut_plan.json` and the master's beat sheet by mapping
through the range map — nothing is retyped, and the spec fields (media, bullets, kicker,
caps) are carried through so the cutdown's caption mutes and coverage match the master's.
"""
import json, os, shutil, sys
sys.path.insert(0, '.')
import beats as BT

FPS = 30000/1001
P = json.load(open('cut_plan.json'))['ranges']
TOTAL = json.load(open('cut_plan.json'))['frames']
DUR = TOTAL/FPS
os.makedirs('cut/logs', exist_ok=True)


def m(t, edge=False):
    """Master time -> cutdown time, or None if it was dropped."""
    for p in P:
        if p['src0'] - (1e-6 if not edge else 0.02) <= t <= p['src1'] + (1e-6 if not edge else 0.02):
            return p['dst0'] + (t - p['src0'])
    return None


def carry(items):
    out = []
    for b in items:
        for p in P:
            a0, a1 = max(b['t0'], p['src0']), min(b['t1'], p['src1'])
            if a1 - a0 < 0.04: continue
            c = dict(b)
            c['t0'] = round(p['dst0'] + (a0 - p['src0']), 4)
            c['t1'] = round(p['dst0'] + (a1 - p['src0']), 4)
            out.append(c)
    return sorted(out, key=lambda x: x['t0'])


def main():
    tl, ov = BT.timeline()
    base = carry([b for b in tl if b['kind'] != 'talk'])
    # ⚠ AN OVERLAY WHOSE START LIES IN DROPPED MATERIAL MUST NOT SURVIVE (lesson A6.15).
    # His lower thirds outlive their sentence by more than a second, so a range that opens
    # part-way through one would print it over a completely different line.
    keep = []
    for o in ov:
        if m(o['t0']) is None: continue          # started in dropped material -> gone
        for p_ in P:                              # else CLAMP to the range it starts in
            a0, a1 = max(o['t0'], p_['src0']), min(o['t1'], p_['src1'])
            if a1 - a0 <= 0.02: continue
            c = dict(o)
            c['t0'] = round(p_['dst0'] + (a0 - p_['src0']), 4)
            c['t1'] = round(p_['dst0'] + (a1 - p_['src0']), 4)
            keep.append(c); break
    overlays = sorted(keep, key=lambda x: x['t0'])
    flashes = [(round(m(a), 4), round(m(b), 4)) for a, b in BT.FLASHES
               if m(a) is not None and m(b) is not None]
    pushes = [tuple(round(m(x), 4) for x in q) for q in BT.PUSHES
              if all(m(x) is not None for x in q)]
    seams = [p['dst0'] for p, q in zip(P[1:], P[:-1]) if abs(p['src0'] - q['src1']) > 1e-3]

    src = f'''#!/usr/bin/env python3
"""GENERATED by sqcut_build.py -- the CUTDOWN's beat sheet, mapped from the master's through
cut_plan.json. Do not edit: regenerate it."""
import json, os
_H = os.path.dirname(os.path.abspath(__file__))     # paths resolve NEXT TO THIS FILE, never
DUR = {DUR!r}                                        # against the caller's cwd (lesson A6.18)
BEATS = {base!r}
LOWER_THIRDS = {[o for o in overlays if o['kind'] == 'lt']!r}
CTAS = {[o for o in overlays if o['kind'] == 'cta']!r}
INSETS = []
FLASHES = {flashes!r}
PUSHES = {pushes!r}
PUSH_Z = {BT.PUSH_Z!r}
SEAMS = {seams!r}
NO_CAPS_KINDS = {BT.NO_CAPS_KINDS!r}
BASE_KINDS = {BT.BASE_KINDS!r}

def timeline():
    base = sorted([b for b in BEATS if b['kind'] in BASE_KINDS], key=lambda b: b['t0'])
    fixed, t = [], 0.0
    for b in base:
        b = dict(b)
        b['t0'] = max(b['t0'], t)
        if b['t1'] - b['t0'] < 0.20: continue
        gap = b['t0'] - t
        if gap > 0.40: fixed.append(dict(kind='talk', t0=round(t, 3), t1=round(b['t0'], 3)))
        elif gap > 0:  b['t0'] = t
        fixed.append(b); t = b['t1']
    if DUR - t > 0.10: fixed.append(dict(kind='talk', t0=round(t, 3), t1=DUR))
    return fixed, LOWER_THIRDS + CTAS + INSETS

def push_at(t):
    best = 0.0
    for a1, a2, b1, b2 in PUSHES:
        k = 1.0 if a2 <= a1 else max(0.0, min(1.0, (t - a1) / (a2 - a1)))
        ko = 0.0 if b2 <= b1 else max(0.0, min(1.0, (t - b1) / (b2 - b1)))
        r = min(k, 1 - ko)
        if t < a1: r = 0.0
        best = max(best, r * r * (3 - 2 * r))
    return 1.0 + (PUSH_Z - 1.0) * best
'''
    open('cut/beats.py', 'w').write(src)

    for f in ('centering.py', 'sqhairgate.py', 'caption_sync_check.py', 'watch.py',
              'watch_mark.py', 'sqlib.py', 'sqassets.py', 'grade.py'):
        shutil.copyfile(f, os.path.join('cut', os.path.basename(f)))
    if not os.path.exists('cut/rc'):
        shutil.copytree('rc', 'cut/rc')
    # ⚠ cut/words_ctc.json IS SQCUTDOWN'S, NOT OURS. This used to re-derive it from cut_plan.json
    # (5-decimal numbers) and drop any word whose two ends did not both map -- both differences from
    # the list the render actually burned. One word landed on the other side of groups()' 0.15 s mute
    # slack and the subtitle gate then graded a grouping that was never rendered. Written once, by
    # the builder, from the same list it hands to captions.render().
    out = json.load(open('cut/words_ctc.json')) if os.path.exists('cut/words_ctc.json') else []
    shutil.copyfile('captions.py', 'cut/captions.py')

    cfg = json.load(open('qc.json'))
    cfg['target_seconds'] = round(TOTAL/FPS, 6)
    cfg['his_mix'] = 'his_mix.wav'
    cfg['captions'] = 'captions.mov'
    cfg['max_static'] = 16.0
    json.dump(cfg, open('cut/qc.json', 'w'), indent=1)

    print(f'cut/beats.py: {len(base)} non-talk beats, {len(overlays)} overlays, '
          f'{len(flashes)} flashes, {len(pushes)} pushes, {len(seams)} seams, '
          f'DUR {DUR:.3f}s / {TOTAL} frames')
    print(f'cut/words_ctc.json: {len(out)} words (written by sqcutdown.py, not re-derived here)')


if __name__ == '__main__':
    main()
