"""RO-06 visual plan. Every item is anchored to the words Dan says (phrase -> output time via words_out.json).
HyperFrames templates (from_plan.py): lt (Motivation lower third), scene/fact (photo + glass price card), l3 (3A side list).
clip = full-frame cutaway, hard cuts. Order of preference kept: Dan's own B-roll (B####), existing library AI (A####),
stock, new AI last (none needed; the six product pictures are Codex stills, labelled). No clip source is used twice."""
AS = "/Volumes/Extreme/_edit_work/ro06/assets"
SHOOT = "/Volumes/Extreme/abs by ai 8:3 jeff chagrin shoot/main camera"
PLAN = [
 # ---------------- hook
 dict(id="C01", kind="clip", start="This is a setup I personally", end="during that time", tail=0.14, src=["B0436@2.0", "B0447@1.0", "B0439@0.5"],
      note="Dan's own B-roll, three different exercises with this setup (round 2): ab wheel rollout, jump rope, kettlebell (lawn)"),
 dict(id="G01", kind="lt", start="So this is great", end="limited time to work out", topic="HOME WORKOUT ON A BUDGET",
      point="A Full Home Setup For $58.", parts=[["A Full Home Setup", "So this is great"], ["For $58.", "for you guys"]]),
 dict(id="C02", kind="clip", start="then you need something like this", end="work out at home", tail=0.2, src=[f"{SHOOT}/C1557.MP4@3.0"], grade="C1559",
      note="the real equipment laid out on the mat (C1557, this shoot's own static shot)"),
 # ---------------- excuses
 dict(id="G02", kind="lt", start="Super cheap, super easy", end="not doing this", tail=0.25, topic="NO MORE EXCUSES",
      point="No Gym Membership. No COMMUTE.", parts=[["No Gym Membership.", "Super cheap"], ["No COMMUTE.", "super easy"]]),
 dict(id="G03", kind="lt", start="you have an emergency", end="whenever you want", topic="ALREADY HAVE A GYM?",
      point="This Is Your BACKUP Setup.", parts=[["This Is Your BACKUP Setup.", "emergency"]]),
 dict(id="G04", kind="lt", start="in the description below", end="recommended items", topic="LINKS IN THE DESCRIPTION",
      point="Every Item I Recommend Is LINKED Below.", parts=[["Every Item I Recommend", "in the description"], ["Is LINKED Below.", "Amazon Associates"]]),
 # ---------------- 1 yoga mat
 dict(id="G05", kind="lt", start="The first thing you need to buy", end="make that it", topic="BASIC SETUP: ITEM 1 OF 4",
      point="A Basic YOGA MAT.", parts=[["A Basic YOGA MAT.", "yoga mat"]]),
 dict(id="C03", kind="clip", start="a lot of these exercises", end="doing on the floor", tail=0.3, src=["B0461@1.0"], note="Dan's B-roll: push-ups on a mat by the pool"),
 dict(id="F01", kind="scene", scene="fact", start="I'm linking you to my recommended", end="one for $22", tail=0.9, photo=f"{AS}/card_mat.png", label="AI-GENERATED",
      eyebrow=["BASIC YOGA MAT", "I'm linking"], headline=[["$22", "22"]],
      detail=["Thin, basic, cheap.", "cheap basic"], push=1.05, drift=-8),
 dict(id="G06", kind="lt", start="but I still regret", end="cheap basic ones", topic="MY MISTAKE",
      point="The Thick Mat Cost $10 More. NO Difference.", parts=[["The Thick Mat Cost $10 More.", "but I still regret"], ["NO Difference.", "doesn't make any difference"]]),
 dict(id="C04", kind="clip", start="lunges a little bit harder", end="a little bit more", tail=0.2, src=["B0462@1.0"], note="Dan's B-roll: walking lunges on a yoga mat"),
 # ---------------- 2 push-up handles
 dict(id="G07", kind="lt", start="so the next item that you need", end="see right here", topic="BASIC SETUP: ITEM 2 OF 4",
      point="PUSH-UP HANDLES.", parts=[["PUSH-UP HANDLES.", "push"]]),
 dict(id="F02", kind="scene", scene="fact", start="I would buy these cheap ones", end="right now for $10", tail=0.8, photo=f"{AS}/card_handles.png", label="AI-GENERATED",
      eyebrow=["PUSH-UP HANDLES", "I would buy"], headline=[["$10", "10"]],
      detail=["Not the $40 rotating ones.", "right now"], push=1.05, drift=-8),
 dict(id="C05", kind="clip", start="But this is gonna give you extra range", end="much more effective contraction", tail=0.2, src=["B0452@0.5"],
      note="Dan's B-roll: push-ups on the handles, side on (the extra depth he is describing)"),
 dict(id="G08", kind="lt", start="It's gonna make the push", end="30, 40 reps", topic="WHY HANDLES",
      point="Deeper Range Of Motion. HARDER Push-Ups.", parts=[["Deeper Range Of Motion.", "It's gonna make"], ["HARDER Push-Ups.", "Especially once"]]),
 # ---------------- 3 jump rope
 dict(id="G09", kind="lt", start="So here's the next thing", end="essential because", topic="BASIC SETUP: ITEM 3 OF 4",
      point="A JUMP ROPE.", parts=[["A JUMP ROPE.", "jump rope"]]),
 dict(id="C06", kind="clip", start="excellent cardio", end="few dollars to get it", tail=0.2, src=["B0430@1.0"], note="Dan's B-roll: jump rope by the pool"),
 dict(id="G10", kind="lt", start="I bought all kinds of expensive", end="get the job done", topic="KEY POINT",
      point="Skip The Speed Ropes. Cheap And Basic WORKS.", parts=[["Skip The Speed Ropes.", "I bought all kinds"], ["Cheap And Basic WORKS.", "cheap and basic"]]),
 # ---------------- 4 ab wheel
 dict(id="G11", kind="lt", start="next thing that you need is our", end="underestimate the ab wheel", topic="BASIC SETUP: ITEM 4 OF 4",
      point="THE AB WHEEL.", parts=[["THE AB WHEEL.", "the ab wheel"]]),
 dict(id="C07", kind="clip", start="but this is one of the best devices", end="exercise your abs", tail=0.3, src=["B0427@0.5"], note="Dan's B-roll: ab wheel rollout by the pool"),
 dict(id="G12", kind="lt", start="It's very simple and it's continuous", end="you get no breaks", topic="WHY IT WORKS",
      point="Continuous Tension. NO Breaks.", parts=[["Continuous Tension.", "continuous tension"], ["NO Breaks.", "no breaks"]]),
 dict(id="F03", kind="scene", scene="fact", start="The ab wheel costs about", end="on screen right now", tail=0.6, photo=f"{AS}/card_wheel.png", label="AI-GENERATED",
      eyebrow=["BASIC AB WHEEL", "The ab wheel costs"], headline=[["$17", "17"]],
      detail=["No need for a fancy one.", "recommended one"], push=1.05, drift=-8),
 # ---------------- basic total
 dict(id="L01", kind="l3", start="Yoga mat, $22", end="get the job done", heading="Basic Setup: $58",
      points=["Yoga mat: $22", "Push-up handles: $10", "Jump rope: $9", "Ab wheel: $17"], reveal=["Yoga mat", "Push", "Jump rope", "ab wheel"]),
 dict(id="C08", kind="clip", start="Even if you only have five minutes", end="two minutes a day to work out", tail=0.2, src=["B0460@1.0"], note="Dan's B-roll: bodyweight squats by the pool (a quick home workout)"),
 # ---------------- 5 kettlebell
 dict(id="G13", kind="lt", start="But I know most of you guys", end="good home setup", topic="GOT A LITTLE MORE MONEY?",
      point="The Intermediate Setup: 3 MORE Items.", parts=[["The Intermediate Setup:", "But I know most"], ["3 MORE Items.", "couple hundred"]]),
 dict(id="G14", kind="lt", start="is a kettlebell", end="variety of other exercises", topic="INTERMEDIATE: ITEM 5",
      point="A KETTLEBELL.", parts=[["A KETTLEBELL.", "kettlebell"]]),
 dict(id="F04", kind="scene", scene="fact", start="So, this kettlebell, you can pick up", end="about $45", tail=0.4, cover_shot=True, photo=f"{AS}/card_kettlebell.png", label="AI-GENERATED",
      eyebrow=["35 LB KETTLEBELL", "this kettlebell"], headline=[["$45", "45"]],
      detail=["Right for most beginners.", "most beginners"], push=1.05, drift=-8),
 dict(id="G15", kind="lt", start="So the weight of kettlebell that I recommend", end="using the kettlebell for", topic="WHICH WEIGHT?",
      point="30 Seconds Of Deadlifts Should EXHAUST You.", parts=[["30 Seconds Of Deadlifts", "30 seconds of kettlebell"], ["Should EXHAUST You.", "exhausts"]]),
 dict(id="G16", kind="lt", start="Number one it uses your entire body", end="just like the regular deadlift", topic="KETTLEBELL DEADLIFT",
      point="Back, Legs, Arms, Abs: Your WHOLE Body.", parts=[["Back, Legs, Arms, Abs:", "your back"], ["Your WHOLE Body.", "everything will be"]]),
 dict(id="G17", kind="lt", start="But I do these kettlebell deadlifts", end="do things wrong", topic="KEY POINT",
      point="Kettlebell Deadlifts: Much LOWER Risk.", parts=[["Kettlebell Deadlifts:", "But I do these"], ["Much LOWER Risk.", "lower risk"]]),
 dict(id="G18", kind="lt", start="if you buy a full set of barbells", end="heavier kettlebell", topic="THE PRICE GAP",
      point="Barbell Set: $500 To $1,000. Kettlebell: $45.", parts=[["Barbell Set: $500 To $1,000.", "five hundred"], ["Kettlebell: $45.", "but this will just"]]),
 dict(id="C10", kind="clip", start="you can progress to this kettlebell swings", end="for that weight", tail=0.2, src=["B0431@1.0"], note="Dan's B-roll: kettlebell swings by the pool"),
 dict(id="G19", kind="lt", start="you should buy basic prison", end="rubber coating", topic="KEY POINT",
      point="Skip The $100 Coated One. Buy Basic IRON.", parts=[["Skip The $100 Coated One.", "you should buy"], ["Buy Basic IRON.", "black iron"]]),
 # ---------------- 6 medicine ball
 dict(id="G20", kind="lt", start="next thing that you need is a medicine", end="workout exercises", topic="INTERMEDIATE: ITEM 6",
      point="A MEDICINE BALL.", parts=[["A MEDICINE BALL.", "medicine"]]),
 dict(id="C11", kind="clip", start="is toe touches", end="that exercise yet", tail=0.2, src=["B0434@0.5"], note="Dan's B-roll: medicine ball toe touches by the pool"),
 dict(id="G21", kind="lt", start="Now the mistake that most people make", end="only four pounds", topic="THE COMMON MISTAKE",
      point="Buying One That's Too HEAVY. Mine Is 4 lb.", parts=[["Buying One That's Too HEAVY.", "Now the mistake"], ["Mine Is 4 lb.", "the one that I have"]]),
 dict(id="F05", kind="scene", scene="fact", start="So what you're seeing on screen right now", end="most people", tail=0.3, photo=f"{AS}/card_medball.png", label="AI-GENERATED",
      eyebrow=["MEDICINE BALL", "So what you're seeing"], headline=[["6 lb", "six"]],
      detail=["About $20.", "right for"], push=1.05, drift=-8),
 dict(id="C12", kind="clip", start="it doesn't slam on the ground", end="in that repetition", tail=0.2, src=["B0467@1.0"], note="Dan's B-roll: lying toe-touch crunches (the ball coming back to the ground)"),
 dict(id="G22", kind="lt", start="but if you want to save money", end="dumbbell instead", topic="SAVE MONEY HERE",
      point="A 5 lb Plate Or Dumbbell Works TOO.", parts=[["A 5 lb Plate Or Dumbbell", "but if you want"], ["Works TOO.", "Just use"]]),
 # ---------------- 7 dumbbells
 dict(id="G23", kind="lt", start="so the next thing that you need to buy is some", end="essential arm exercise", topic="INTERMEDIATE: ITEM 7",
      point="DUMBBELLS.", parts=[["DUMBBELLS.", "dumbbells"]]),
 dict(id="F06", kind="scene", scene="fact", start="it's going to run you about $29", end="scale with the weight", tail=0.3, photo=f"{AS}/card_dumbbells.png", label="AI-GENERATED",
      eyebrow=["25 LB DUMBBELLS", "it's going to run"], headline=[["$29", "29"]],
      detail=["Heavier costs more.", "like with the kettlebell"], push=1.05, drift=-8),
 dict(id="G24", kind="lt", start="So if you can only afford one pair", end="showed you on screen", topic="ONLY BUYING ONE PAIR?",
      point="Pick Your CURL Weight: About 25 lb.", parts=[["Pick Your CURL Weight:", "So if you can only"], ["About 25 lb.", "25 pounds"]]),
 dict(id="G25", kind="lt", start="What I recommend is a weight that's challenging", end="30 seconds of side laterals", topic="BUYING TWO PAIRS?",
      point="Add A LIGHT Pair For Side Laterals.", parts=[["Add A LIGHT Pair", "lighter weight"], ["For Side Laterals.", "side laterals"]]),
 dict(id="C13", kind="clip", start="These side laterals are important", end="in a home workout", tail=0.2, src=["B0450@0.5"], note="Dan's B-roll: dumbbell side laterals by the pool"),
 dict(id="G31", kind="lt", start="In that case, I recommend a heavy pair", end="40 or 45 pounds", topic="BUYING THREE PAIRS?",
      point="Add A HEAVY Pair For Triceps: 40 To 45 lb.", parts=[["Add A HEAVY Pair For Triceps:", "heavy pair"], ["40 To 45 lb.", "40 or 45"]]),
 dict(id="G32", kind="lt", start="So I would say those are the most important", end="light for your side laterals", topic="THE 3 PAIRS TO BUY",
      point="Heavy: Triceps. Medium: Curls. Light: LATERALS.", parts=[["Heavy: Triceps.", "heavy for triceps"], ["Medium: Curls.", "medium for curls"], ["Light: LATERALS.", "light for your"]]),
 # ---------------- intermediate recap
 dict(id="G33", kind="lt", start="the kettlebell good for", end="weight that you're using", topic="INTERMEDIATE SETUP",
      point="Kettlebell $45. Ball $20. Dumbbells $29.", parts=[["Kettlebell $45.", "the kettlebell good"], ["Ball $20.", "Your medicine ball"], ["Dumbbells $29.", "your dumbbells"]]),
 dict(id="G26", kind="lt", start="Everything in this intermediate setup", end="about $150", topic="THE FULL SETUP",
      point="$58 + $94 = About $150 For EVERYTHING.", parts=[["$58 + $94", "94"], ["= About $150 For EVERYTHING.", "150"]]),
 dict(id="C14", kind="clip", start="This stuff will make a huge difference", end="in your life", tail=0.1, src=["B0473@0.5", "B0474@0.5"], note="Dan's B-roll: his dumbbell, then his kettlebell and ab wheel, low angle"),
 # ---------------- towel
 dict(id="G27", kind="lt", start="You will also need a towel", end="hand towels like this", topic="ONE MORE THING",
      point="A Few Strong HAND TOWELS.", parts=[["A Few Strong HAND TOWELS.", "towel"]]),
 dict(id="C15", kind="clip", start="we're going to be doing things like these towel rows", end="with the towel", tail=0.3, src=["B0465@1.0"], note="Dan's B-roll: towel pull-aparts"),
 # ---------------- caveats
 dict(id="G28", kind="lt", start="so that's how you build a basic", end="around 150", topic="RECAP",
      point="Basic Setup: $58. Full Setup: About $150.", parts=[["Basic Setup: $58.", "so that's how you build"], ["Full Setup: About $150.", "great set up"]]),
 dict(id="G29", kind="lt", start="However, I don't want you to stay", end="get a gym membership", topic="KEY POINT",
      point="Start At Home. Then UPGRADE To A Gym.", parts=[["Start At Home.", "However"], ["Then UPGRADE To A Gym.", "more sophisticated"]]),
 dict(id="G34", kind="lt", start="Most important is going to be the barbells", end="that type of thing", topic="WHAT A GYM ADDS",
      point="Barbells. Leg Press. Leg Curl. BUMPER Plates.", parts=[["Barbells.", "the barbells"], ["Leg Press.", "Leg press"], ["Leg Curl.", "leg curl"], ["BUMPER Plates.", "bumper plates"]]),
 dict(id="G30", kind="lt", start="So I want you guys to get started", end="at your house", topic="ACTION STEP",
      point="Buy The Basics NOW. Upgrade When You're READY.", parts=[["Buy The Basics NOW.", "So I want you guys"], ["Upgrade When You're READY.", "Eventually once"]]),
 # ---------------- CTA
 dict(id="P01", kind="clip", start="you're going to upload your current picture", end="where you want to get to", tail=0.1,
      src=["/Users/danielrose/Documents/Claude/Projects/Abs By AI/Media/codex-video-trial/assets/ad/simulated-dan-sunglasses-to-pool/simulated-dan-sunglasses-to-pool-ad14-v1.mp4@0.0"], pending=True,
      note="the approved Dan self-generation demo (sunglasses before to pool goal, AI-GENERATED disclosure kept exactly as approved)"),
 dict(id="P02", kind="clip", start="If you don't have a certain piece of equipment", end="have in place", tail=0.1, src=["B0034@1.0"], pending=True,
      note="real app screen recording: the workout list and an exercise sheet (in the approved phone treatment at full build)"),
]
