"""Local preview only: run after node workboard/tests/preview.js on a fresh fixture."""
from pathlib import Path
import json
from playwright.sync_api import sync_playwright, expect

root=Path(__file__).resolve().parents[2]
out=root/'qa'
out.mkdir(exist_ok=True)
with sync_playwright() as p:
    browser=p.chromium.launch(headless=True)
    ctx=browser.new_context(viewport={'width':3440,'height':1440})
    page=ctx.new_page()
    errors=[]
    page.on('pageerror',lambda e:errors.append(str(e)))
    page.goto('http://127.0.0.1:8842/workboard')
    expect(page.locator('.column')).to_have_count(10)
    expect(page.locator('.card')).to_have_count(0)
    page.screenshot(path=str(out/'workboard-empty.jpg'),type='jpeg',quality=90)
    def saved():
        expect(page.locator('#save-state')).to_contain_text('Saved')
        expect(page.locator('#notice')).to_be_empty()
    def close():
        page.get_by_role('button',name='Close card',exact=True).click()
        expect(page.locator('#card-dialog')).not_to_be_visible()
    def create(title,index=0):
        page.locator('.column').nth(index).get_by_role('button',name='＋ Add card',exact=True).click()
        page.get_by_role('textbox',name='New card title',exact=True).fill(title)
        page.get_by_role('button',name='Create card',exact=True).click()
        expect(page.locator('#card-dialog')).to_be_visible()
        saved()
    create('QA fixture: edit preview')
    page.locator('#card-description').fill('QA fixture only.\nCheck picture, captions and audio.')
    page.locator('#card-due').fill('2026-10-20')
    page.get_by_role('button',name='Add label',exact=True).click()
    page.get_by_label('Label name',exact=True).fill('Video')
    page.get_by_label('Label color',exact=True).select_option(label='Green')
    page.get_by_role('button',name='Add label',exact=True).click()
    page.get_by_label('Label name',exact=True).nth(1).fill('Needs review')
    page.get_by_label('Label color',exact=True).nth(1).select_option(label='Amber')
    page.get_by_role('button',name='Save changes',exact=True).click();saved()
    page.get_by_role('textbox',name='New checklist item',exact=True).fill('Check captions')
    page.get_by_role('button',name='Add item',exact=True).click();saved()
    page.get_by_role('checkbox',name='Check captions',exact=True).check();saved()
    page.get_by_role('textbox',name='New comment',exact=True).fill('QA fixture: opening approved.')
    page.get_by_role('button',name='Add comment',exact=True).click();saved()
    page.locator('#file-input').set_input_files({'name':'qa-notes.txt','mimeType':'text/plain','buffer':b'Private QA notes'})
    expect(page.locator('#attachments a')).to_have_text('qa-notes.txt')
    with page.expect_download() as info:page.locator('#attachments a').click()
    assert Path(info.value.path()).read_bytes()==b'Private QA notes'
    page.locator('#card-title').fill('Unsaved title')
    page.get_by_role('button',name='Close card',exact=True).click()
    expect(page.locator('#confirm-dialog')).to_be_visible()
    page.get_by_role('button',name='Keep editing',exact=True).click()
    expect(page.locator('#card-title')).to_have_value('Unsaved title')
    page.get_by_role('button',name='Close card',exact=True).click()
    page.get_by_role('button',name='Discard changes',exact=True).click()
    page.get_by_role('button',name='Open card: QA fixture: edit preview',exact=True).click()
    expect(page.locator('#card-title')).to_have_value('QA fixture: edit preview')
    page.locator('#move-list').select_option(label='Claude task queue')
    page.get_by_role('button',name='Move card',exact=True).click();saved()
    expect(page.locator('#card-location')).to_have_text('Claude task queue')
    page.set_viewport_size({'width':1920,'height':1400})
    page.screenshot(path=str(out/'workboard-card-qa.jpg'),type='jpeg',quality=90)
    close()
    page.reload();expect(page.locator('.card')).to_have_count(1)
    expect(page.locator('.column').nth(3).locator('.card')).to_have_count(1)
    create('QA fixture: second card',3);close()
    page.set_viewport_size({'width':3440,'height':1440})
    # Actual pointer drag, not a synthetic API reorder.
    first=page.get_by_role('button',name='Open card: QA fixture: second card',exact=True)
    dest=page.get_by_role('button',name='Open card: QA fixture: edit preview',exact=True)
    first.drag_to(dest,target_position={'x':40,'y':8})
    expect(page.locator('.column').nth(3).locator('.card').first).to_have_attribute('aria-label','Open card: QA fixture: second card')
    # Move card across lists with the pointer.
    page.get_by_role('button',name='Open card: QA fixture: second card',exact=True).drag_to(page.locator('.column').nth(2).locator('.cards'),target_position={'x':50,'y':50})
    expect(page.locator('.column').nth(2).locator('.card')).to_have_count(1)
    # Reorder list by pointer and confirm after refresh.
    page.locator('.column').nth(3).locator('.column-head').drag_to(page.locator('.column').first,target_position={'x':20,'y':20})
    expect(page.locator('.column').first.locator('.column-title')).to_contain_text('Claude task queue')
    page.reload();expect(page.locator('.column').first.locator('.column-title')).to_contain_text('Claude task queue')
    # Keyboard / touch list move alternative.
    page.get_by_role('button',name='List menu: Claude task queue',exact=True).click()
    page.get_by_label('List position',exact=True).select_option(index=3)
    page.get_by_role('button',name='Move list',exact=True).click();saved()
    expect(page.locator('.column').nth(3).locator('.column-title')).to_contain_text('Claude task queue')
    page.get_by_role('textbox',name='Search cards',exact=True).fill('second')
    expect(page.locator('.card')).to_have_count(1)
    page.get_by_role('textbox',name='Search cards',exact=True).fill('')
    # Two tabs: stale draft rejected and retained until explicit refresh.
    other=ctx.new_page();other.goto('http://127.0.0.1:8842/workboard');expect(other.locator('.card')).to_have_count(2)
    page.get_by_role('button',name='Open card: QA fixture: edit preview',exact=True).click()
    page.locator('#card-description').fill('My retained draft')
    other.get_by_role('button',name='Open card: QA fixture: edit preview',exact=True).click()
    other.locator('#card-title').fill('QA fixture: changed in another tab')
    other.get_by_role('button',name='Save changes',exact=True).click()
    expect(other.locator('#draft-state')).to_have_text('Saved')
    page.get_by_role('button',name='Save changes',exact=True).click()
    expect(page.locator('#dialog-notice')).to_contain_text('another tab')
    expect(page.locator('#card-description')).to_have_value('My retained draft')
    page.get_by_role('button',name='Reload latest',exact=True).click()
    expect(page.locator('#card-activity')).to_contain_text('Latest saved title: QA fixture: changed in another tab')
    expect(page.locator('#card-description')).to_have_value('My retained draft')
    page.locator('#card-title').fill('QA fixture: changed in another tab')
    page.get_by_role('button',name='Save changes',exact=True).click();saved()
    other.close()
    page.get_by_role('button',name='Archive card',exact=True).click()
    expect(page.locator('#card-dialog')).not_to_be_visible()
    expect(page.locator('.card')).to_have_count(1)
    page.get_by_role('button',name='Archive',exact=True).click()
    page.get_by_role('button',name='Restore card',exact=True).click()
    expect(page.locator('#panel-body')).to_contain_text('Nothing archived')
    page.get_by_role('button',name='Close panel',exact=True).click()
    expect(page.locator('.card')).to_have_count(2)
    page.get_by_role('button',name='List menu: Claude task queue',exact=True).click()
    page.get_by_role('button',name='Archive list',exact=True).click();saved()
    expect(page.locator('.column')).to_have_count(9)
    page.get_by_role('button',name='Archive',exact=True).click()
    page.get_by_role('button',name='Restore list',exact=True).click()
    page.get_by_role('button',name='Close panel',exact=True).click()
    expect(page.locator('.column')).to_have_count(10)
    page.get_by_role('button',name='＋ Add list',exact=True).click()
    page.get_by_label('List name',exact=True).fill('QA temporary list')
    page.get_by_role('button',name='Create list',exact=True).click();saved()
    expect(page.locator('.column')).to_have_count(11)
    page.get_by_role('button',name='List menu: QA temporary list',exact=True).click()
    page.get_by_label('List name',exact=True).fill('QA renamed list')
    page.get_by_role('button',name='Rename list',exact=True).click();saved()
    page.get_by_role('button',name='List menu: QA renamed list',exact=True).click()
    page.get_by_role('button',name='Archive list',exact=True).click();saved()
    # Focus and responsive bounds.
    page.get_by_role('textbox',name='Search cards',exact=True).focus();page.keyboard.press('Tab')
    assert page.evaluate('document.activeElement.matches(":focus-visible")')
    metrics=[]
    for width,height in [(3440,1440),(1440,1000),(390,844)]:
        page.set_viewport_size({'width':width,'height':height})
        row=page.evaluate('({viewport:innerWidth,body:document.body.scrollWidth,header:document.querySelector(".topbar").getBoundingClientRect().height,board:document.querySelector(".board").getBoundingClientRect().y})')
        assert row['body']==width,row
        metrics.append(row)
        page.screenshot(path=str(out/('workboard-qa-'+str(width)+'.jpg')),type='jpeg',quality=90)
    # Real touch emulation, menu alternative available and operable.
    touch=browser.new_context(viewport={'width':390,'height':844},is_mobile=True,has_touch=True)
    t=touch.new_page();t.goto('http://127.0.0.1:8842/workboard')
    t.get_by_role('button',name='List menu: Unassigned tasks',exact=True).tap()
    t.get_by_label('List position',exact=True).select_option(index=1)
    t.get_by_role('button',name='Move list',exact=True).tap()
    expect(t.locator('.column').nth(1).locator('.column-title')).to_contain_text('Unassigned tasks')
    touch.close()
    assert not errors,errors
    (out/'browser-results.json').write_text(json.dumps({'passed':True,'metrics':metrics,'pageErrors':errors},indent=2))
    print('PASS: browser create/edit/cancel, checklist/comments/attachment download, drag cards within and across lists, drag lists, saved refresh, keyboard/touch moves, archive/restore, search, two-tab conflict retains draft, 3440/1440/390 layouts, no JS errors.')
    browser.close()
