#!/usr/bin/env python3
"""GENERATED by sqcut_build.py -- the CUTDOWN's beat sheet, mapped from the master's through
cut_plan.json. Do not edit: regenerate it."""
import json, os
_H = os.path.dirname(os.path.abspath(__file__))     # paths resolve NEXT TO THIS FILE, never
DUR = 49.816433333333336                                        # against the caller's cwd (lesson A6.18)
BEATS = [{'kind': 'bleed', 't0': 0.0, 't1': 2.9363, 'media': 'ai_goal_plain'}, {'kind': 'card', 't0': 2.95, 't1': 6.7401, 'media': 'before_200lb', 'kicker': '200 pounds', 'caps': False}, {'kind': 'bleed', 't0': 11.45, 't1': 12.4, 'media': 'today_towel'}, {'kind': 'bleed', 't0': 12.4, 't1': 13.3467, 'media': 'today_trees'}, {'kind': 'winmedia', 't0': 13.3616, 't1': 18.5116, 'media': 'app_flow_a'}, {'kind': 'card', 't0': 18.5116, 't1': 20.7116, 'media': 'after_reveal'}, {'kind': 'window', 't0': 26.1261, 't1': 31.3177, 'header': None, 'bullets': ['You can generate an AI image of yourself with ripped six-pack abs', 'COMPLETELY FREE']}, {'kind': 'card', 't0': 34.1675, 't1': 35.5127, 'media': 'ai_women_pool', 'label': 'AI-GENERATED'}, {'kind': 'card', 't0': 35.5127, 't1': 36.8627, 'media': 'ai_respect_gym', 'label': 'AI-GENERATED'}, {'kind': 'card', 't0': 36.8627, 't1': 37.8044, 'media': 'ai_beachrun', 'label': 'AI-GENERATED'}, {'kind': 'window', 't0': 37.8044, 't1': 45.5455, 'header': None, 'bullets': ['Generating an image of yourself with abs is the first step.', 'Our personalized AI fitness program helps you make it real.']}]
LOWER_THIRDS = []
CTAS = [{'kind': 'cta', 't0': 33.2677, 't1': 34.1675, 'top': 'Get A FREE AI Image Of Yourself', 'big': 'With Abs'}, {'kind': 'cta', 't0': 48.4506, 't1': 49.8164, 'top': 'Get A FREE AI Image Of Yourself', 'big': 'With Abs'}]
INSETS = []
FLASHES = [(6.64, 7.08), (20.6016, 21.0416)]
PUSHES = [(0.0, 0.0, 2.6, 2.78), (10.55, 11.05, 12.2, 12.3), (20.9616, 21.4616, 23.7616, 24.5116), (45.4506, 46.0506, 48.3006, 49.0006)]
PUSH_Z = 1.2
SEAMS = [13.34667, 26.1261, 34.16747, 37.80443]
NO_CAPS_KINDS = {'cta', 'title', 'stmt', 'window'}
BASE_KINDS = {'bleed', 'title', 'stmt', 'card', 'winmedia', 'talk', 'window'}

def timeline():
    base = sorted([b for b in BEATS if b['kind'] in BASE_KINDS], key=lambda b: b['t0'])
    fixed, t = [], 0.0
    for b in base:
        b = dict(b)
        b['t0'] = max(b['t0'], t)
        if b['t1'] - b['t0'] < 0.20: continue
        gap = b['t0'] - t
        if gap > 0.40: fixed.append(dict(kind='talk', t0=round(t, 3), t1=round(b['t0'], 3)))
        elif gap > 0:  b['t0'] = t
        fixed.append(b); t = b['t1']
    if DUR - t > 0.10: fixed.append(dict(kind='talk', t0=round(t, 3), t1=DUR))
    return fixed, LOWER_THIRDS + CTAS + INSETS

def push_at(t):
    best = 0.0
    for a1, a2, b1, b2 in PUSHES:
        k = 1.0 if a2 <= a1 else max(0.0, min(1.0, (t - a1) / (a2 - a1)))
        ko = 0.0 if b2 <= b1 else max(0.0, min(1.0, (t - b1) / (b2 - b1)))
        r = min(k, 1 - ko)
        if t < a1: r = 0.0
        best = max(best, r * r * (3 - 2 * r))
    return 1.0 + (PUSH_Z - 1.0) * best
