from pathlib import Path
import json,re,base64,shutil
ROOT=next(p for p in Path(__file__).resolve().parents if (p/'AGENTS.md').exists());S=ROOT/'scripts/covers/trial-campaign-20261001';R=ROOT/'social media graphics/youtube/thumbnails/_trial-campaign-20261001/round2'
css=(S/'review-template.html').read_text().split('<style>')[1].split('</style>')[0]
css+='\n.phone-mode .picture img{max-width:320px!important;height:auto!important}.picture img{max-height:none}.picture img.tall{max-height:600px}.source a{display:inline-block;margin-top:6px}.ai{background:#634935;color:#ffe0b8}.picture{min-height:0}.decisions strong{color:white}'
manifest=json.loads((R/'manifest.json').read_text())
html='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Trial Campaign AD Thumbnails R2</title><style>CSS</style></head><body><main><header><div class="eyebrow">Abs By AI / Round 2 / October 1, 2026</div><h1>Your six revisions.<br>Ready for your picks.</h1><p class="intro">Nine revised choices, plus the unchanged B comparisons for Ads 4 and 6. Choose one per ad. Recommendations are creative judgments, not measured CTR winners.</p><div class="pills"><span class="pill">11 selectable choices</span><span class="pill">15 review layouts</span><span class="pill">3 Codex subscription generations</span><span class="pill">Review only</span></div></header>
<section class="decisions"><h2>What I decided (overrule anything)</h2><ul>
<li><strong>Ad 13:</strong> your original pool photo in all three B-style choices: expense props, robot trainer, and AI savings. Pick: <strong>13-R2B</strong>, the robot makes the trainer replacement easiest to see.</li>
<li><strong>RA-01:</strong> E's studio-blue-53 portrait in C's purple design. Pick: <strong>RA-R2A</strong>.</li>
<li><strong>Ad 10:</strong> D's studio-white-25 jeans-and-glasses portrait in B's orange office design. Pick: <strong>10-R2A</strong>.</li>
<li><strong>Ad 4:</strong> keep original B and add studio-gray-55's real sideways smirk. Pick: <strong>4-R2A</strong>, the expression supports the headline.</li>
<li><strong>Ad 3:</strong> reuse RA-01 B's cyan phone design and studio-blue-173, with Ad 3 B's exact copy. Pick: <strong>3-R2A</strong>.</li>
<li><strong>Ad 6:</strong> keep original B, add studio-blue-171 in jeans and glasses, and age the original studio-blue-221 face and hair. Pick: <strong>6-R2A</strong>, the approachable real-photo option.</li></ul><p>All headline wording is preserved. The age edit changes only hair, face and neck; the original body, hands and clothing remain. No final exports or installation until you choose.</p></section>
<nav><a href="#ad13">Ad 13</a><a href="#ra01">RA-01</a><a href="#ad10">Ad 10</a><a href="#ad4">Ad 4</a><a href="#ad3">Ad 3</a><a href="#ad6">Ad 6</a><a href="#reply">Your picks</a><button id="phone">Show at phone size</button></nav><div id="ads"></div>
<section class="reply" id="reply"><h2>Your picks</h2><p>Select one option per ad, then copy the reply into chat. These controls only save your choices in this browser.</p><textarea id="answer" aria-label="Round 2 thumbnail picks"></textarea><button id="copy">Copy picks</button> <button id="clear">Clear picks</button><span id="copied" role="status"></span></section><footer>Review only. Campaign 24316364155. <a href="manifest.json">Source and layout record</a>.</footer></main><dialog id="zoom"><button id="close">Close</button><img alt="Enlarged thumbnail" id="zoomImage"></dialog>
<script>
const data=MANIFEST;const embedded=EMBEDDED;const key='trial-thumbnails-20261001-round2-v1';const asset=p=>embedded[p]||p;const ads=data.ads;let picks={};try{picks=JSON.parse(localStorage.getItem(key)||'{}')}catch{};for(const a of ads){if(!a.choices.some(c=>c.id===picks[a.id]))delete picks[a.id]}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const path=(id,aspect)=>`options/${id}-${aspect}.jpg`;
function reply(){document.querySelector('#answer').value='Trial Campaign AD Thumbnails R2 picks:\\n'+ads.map(a=>`${a.id==='ra01'?'RA-01':a.id.replace('ad','Ad ')}: ${picks[a.id]||'[choose an option]'}`).join('\\n')+'\\n\\nChanges or challengers: ';}
function select(id,choice){picks[id]=choice;try{localStorage.setItem(key,JSON.stringify(picks))}catch{}document.querySelectorAll(`[data-ad="${id}"]`).forEach(c=>{let yes=c.dataset.choice===choice;c.classList.toggle('selected',yes);c.querySelector('.choose').textContent=(yes?'Selected ':'Choose ')+c.dataset.choice});reply();}
document.querySelector('#ads').innerHTML=ads.map(a=>`<section class="section" id="${a.id}"><h2>${esc(a.name)}</h2><div class="rec"><strong>My pick: ${a.recommend}.</strong> ${esc(a.why)}</div><div class="grid">${a.choices.map(c=>`<article class="card ${a.recommend===c.id?'recommended':''} ${picks[a.id]===c.id?'selected':''}" data-ad="${a.id}" data-choice="${c.id}"><div class="picture"><img src="${asset(path(c.id,'16x9'))}" alt="${c.id}: ${esc(c.headline.join(' '))}"></div><div class="body"><div class="label"><h3>${c.id}</h3>${a.recommend===c.id?'<span class="tag">MY PICK</span>':''}</div><div class="slot">${esc(c.title)}</div>${c.age?'<span class="tag ai">AI age edit</span>':''}<p>${esc(c.note)}</p><div class="source">Photo: ${c.photo}<br>Original design: ${c.reference}<br><a class="ref" href="${asset('references/'+c.reference+'-16x9.jpg')}">View original design</a></div><div class="actions">${c.aspects.map((aspect,j)=>`<button class="aspect ${j===0?'active':''}" data-aspect="${aspect}">${aspect.replace('x',':')}</button>`).join('')}<button class="enlarge">Enlarge</button></div><button class="choose">${picks[a.id]===c.id?'Selected ':'Choose '}${c.id}</button></div></article>`).join('')}</div></section>`).join('');
reply();document.querySelectorAll('.choose').forEach(b=>b.onclick=()=>{const c=b.closest('.card');select(c.dataset.ad,c.dataset.choice)});document.querySelectorAll('.aspect').forEach(b=>b.onclick=()=>{const c=b.closest('.card'),img=c.querySelector('img'),a=b.dataset.aspect;img.src=asset(path(c.dataset.choice,a));img.className=a==='9x16'?'tall':a==='1x1'?'square':'';c.querySelectorAll('.aspect').forEach(x=>x.classList.toggle('active',x===b))});
function zoom(src){document.querySelector('#zoomImage').src=src;document.querySelector('#zoom').showModal()}
document.querySelectorAll('.picture,.enlarge').forEach(b=>b.onclick=()=>zoom(b.closest('.card').querySelector('img').src));document.querySelectorAll('.ref').forEach(a=>a.onclick=e=>{e.preventDefault();zoom(a.href)});document.querySelector('#close').onclick=()=>document.querySelector('#zoom').close();document.querySelector('#zoom').onclick=e=>{if(e.target.id==='zoom')e.target.close()};document.querySelector('#phone').onclick=()=>{let on=document.body.classList.toggle('phone-mode');document.querySelector('#phone').textContent=on?'Show larger previews':'Show at phone size'};document.querySelector('#clear').onclick=()=>{picks={};try{localStorage.removeItem(key)}catch{}document.querySelectorAll('.card.selected').forEach(c=>{c.classList.remove('selected');c.querySelector('.choose').textContent='Choose '+c.dataset.choice});reply()};document.querySelector('#copy').onclick=async()=>{const t=document.querySelector('#answer');try{await navigator.clipboard.writeText(t.value);document.querySelector('#copied').textContent=' Copied. Paste into chat.'}catch{t.select();document.execCommand('copy');document.querySelector('#copied').textContent=' Copied.'}};
</script></body></html>'''
html=html.replace('CSS',css).replace('MANIFEST',json.dumps(manifest))
(R/'index.html').write_text(html.replace('EMBEDDED','{}'))
embedded={str(p.relative_to(R)):'data:image/jpeg;base64,'+base64.b64encode(p.read_bytes()).decode() for folder in ['options','references'] for p in (R/folder).glob('*.jpg')}
(R/'Review-offline.html').write_text(html.replace('EMBEDDED',json.dumps(embedded)))
print('Review page and self-contained offline copy built.')
