"""RO-13 visual plan. Every item is anchored to the words Dan says (phrase -> output time via words_out.json).
Kinds built from the approved HyperFrames templates (hyperframes/from_plan.py): lt (Motivation lower third, parts land on
their words), scene/fact (before / fact card), l3 (3A side list, items land on their words), cycle (4-step loop card).
Kinds that stay softblue.py: title (full-screen way card), scene/recap, phone (app demo beside Dan). clip = full-frame
cutaway (Pexels / library), hard cuts. start = phrase whose first word starts the item; end = phrase whose last word
ends it (or dur). Inside a template item every time is a phrase too (resolved by from_plan.py)."""
LIB = "/Volumes/Extreme/_asset_library_stage/Abs By AI - Video Asset Library"
ST = "/Volumes/Extreme/_edit_work/ro13/stock"
PH = "/Volumes/Extreme/_edit_work/ro13/assets"
PLAN = [
 # ---------------- hook
 dict(id="A01", kind="ai", ph="A", start="Can you drink alcohol", end="six pack abs", tail=0.25,
      note="AI opener A: a lean man with visible abs at a pool cookout raises a beer and takes a sip (the question, in one picture)"),
 dict(id="G01", kind="lt", start="Yes, you can", end="alcohol consumption", topic="ALCOHOL AND ABS",
      point="Yes, You Can. With RULES.", parts=[["Yes, You Can.", "Yes, you can"], ["With RULES.", "some rules"]]),
 dict(id="A02", kind="ai", ph="B", start="Your training can be perfect", end="nothing changed", tail=0.42,
      note="AI clip B: a heavier man in gym clothes checks his stomach in the bathroom mirror, lets his shirt drop, head down; two beer bottles on the counter"),
 dict(id="G02", kind="l3", start="So I'm going to tell you", end="landed on this myself", heading="In This Video",
      points=["What alcohol really does", "My 6 rules for drinking", "Where I landed myself"],
      reveal=["exactly what alcohol", "my 6 rules", "honest truth"]),
 # ---------------- what alcohol does (4)
 dict(id="G03", kind="lt", start="Number 1, it is pure", end="straight fat", topic="1. LIQUID CALORIES",
      point="7 Calories Per Gram. Almost As Dense As FAT.",
      parts=[["7 Calories Per Gram.", "7 calories per gram"], ["Almost As Dense As FAT.", "almost as calorie"]]),
 dict(id="C01", kind="clip", start="Zero nutrition", end="do not drink it", src=[f"{ST}/p4752641.mp4@2.0"], note="beer filling a glass, close-up"),
 dict(id="G04", kind="lt", start="And I know a lot of you", end="high quality sleep", topic="2. YOUR SLEEP",
      point="Passing Out Fast Is NOT Quality Sleep.",
      parts=[["Passing Out Fast", "knocks you out"], ["Is NOT Quality Sleep.", "is not high quality"]]),
 dict(id="C02", kind="clip", start="Alcohol wrecks your sleep", end="time I drink", src=[f"{ST}/p6944077.mp4@2.0"], note="man sitting up in bed at night, head in his hand, a glass on the nightstand"),
 dict(id="G05", kind="l3", start="Deep sleep collapses", end="no to anything", heading="After You Drink",
      points=["Deep sleep collapses", "Heart rate stays up", "Hungrier the next day", "Less willpower"],
      reveal=["Deep sleep collapses", "heart rate stays", "more hunger", "less willpower"]),
 dict(id="G06", kind="lt", start="Nobody has ever broken", end="drinks themselves", topic="3. YOUR INHIBITIONS",
      point="The Drunk Eating Does MORE Damage.",
      parts=[["The Drunk Eating", "late night drunk"], ["Does MORE Damage.", "more damage"]]),
 dict(id="C03", kind="clip", start="You did not eat 2000", end="4 drinks ago", src=[f"{ST}/p7047793.mp4@1.0"], note="half-eaten pizza box and a crushed can in the dark"),
 dict(id="G07", kind="lt", start="Your body treats alcohol", end="poison is gone", topic="4. RECOVERY AND TESTOSTERONE",
      point="Your Body Treats Alcohol As POISON.", parts=[["Your Body Treats Alcohol As POISON.", "treats alcohol as"]]),
 dict(id="C04", kind="clip", start="That includes building", end="trained for", src=[f"{ST}/p35585667.mp4@2.0"], note="men training at a dumbbell rack"),
 dict(id="G08", kind="scene", scene="fact", start="A heavy weekend", end="consume alcohol", photo=f"{PH}/weekend.jpg",
      eyebrow=["A HEAVY WEEKEND", "A heavy weekend"], headline=[["1 WEEK", "entire week"], ["GONE", "hard training"]],
      detail=["of hard training and dieting.", "hard training"], sweep="dieting", push=1.06, drift=-8),
 # ---------------- the 6 rules
 dict(id="T1", kind="title", start="Rule number 1", dur=2.4, step=1, headline="Eat First"),
 dict(id="G09", kind="lt", start="Wait at least 30", end="break your fast", tail=0.2, topic="RULE 1",
      point="Break Your Fast. Wait 30 MINUTES.", parts=[["Break Your Fast.", "Wait at least"], ["Wait 30 MINUTES.", "30 minutes"]]),
 dict(id="C05", kind="clip", start="Alcohol on an empty", end="damage doing it", src=[f"{ST}/p9003040.mp4@3.0"], note="shots being poured down a row of glasses"),
 dict(id="C06", kind="clip", start="Eat first, wait", end="then drink", src=[f"{ST}/p3134537.mp4@0.5"], note="steak dinner on a plate"),
 dict(id="T2", kind="title", start="Rule number 2", dur=2.4, step=2, headline="Count The Calories"),
 dict(id="G10", kind="scene", scene="fact", start="A real night out", end="in one evening", photo=f"{PH}/night.jpg",
      eyebrow=["A REAL NIGHT OUT", "A real night out"], headline=[["1,000+", "1000 calories"], ["CALORIES", "calories or more"]],
      detail=["A full day's deficit, gone.", "entire day's"], sweep="one evening", push=1.06, drift=-8),
 dict(id="C07", kind="clip", start="in their beers", end="liquor they drank", tail=0.3,
      src=[f"{ST}/p5240991.mp4@2.0", f"{ST}/p11268027.mp4@3.0", f"{ST}/p14058816.mp4@2.0"], note="two beers, a bartender pouring a cocktail, whiskey into a jigger (hard cuts)"),
 dict(id="G11", kind="lt", start="Those calories count", end="feel like tracking", topic="RULE 2",
      point="Untracked Drinks STILL Count.", parts=[["Untracked Drinks STILL Count.", "Those calories count"]]),
 dict(id="C08", kind="clip", start="This is the part where", end="you're done", src=[f"{ST}/p12691894.mp4@3.0"], note="hands photographing a drink and a plate with a phone (stock, not the app)"),
 dict(id="T3", kind="title", start="Rule number three", dur=2.4, step=3, headline="Kill The Sugary Mixers"),
 dict(id="C09", kind="clip", start="Alcohol and liquid sugar", end="same time", tail=0.3, src=[f"{ST}/p8942658.mp4@3.0"], note="bright blue, green and purple cocktails on a bar"),
 dict(id="C10", kind="clip", start="You want dry wine", end="water and lime", tail=0.3, src=[f"{ST}/p10014741.mp4@5.0"], note="soda water with lime in a glass"),
 dict(id="G12", kind="lt", start="When you drink alcohol, it should", end="is not sugary", topic="MY TEST",
      point="If It Tastes BAD, It's Not Sugary.", parts=[["If It Tastes BAD,", "should taste bad"], ["It's Not Sugary.", "it is not sugary"]]),
 dict(id="G13", kind="lt", start="And drinking bad tasting", end="any drunker", topic="THE SECOND BENEFIT",
      point="Bad-Tasting Drinks = You Drink LESS.", parts=[["Bad-Tasting Drinks =", "drinking bad tasting"], ["You Drink LESS.", "You drink less"]]),
 dict(id="C11", kind="clip", start="Most guys don't have six", end="tasted like dessert", src=[f"{ST}/p7603355.mp4@6.0"], note="a margarita being poured into a salt-rimmed glass"),
 dict(id="T4", kind="title", start="Rule number four", dur=2.2, step=4, headline="Cap Your Nights"),
 dict(id="G14", kind="lt", start="One drinking occasion", end="take the edge off", topic="RULE 4",
      point="1 Night A Week. 2 At The MAX.", parts=[["1 Night A Week.", "One drinking occasion"], ["2 At The MAX.", "two at the absolute"]]),
 dict(id="C12", kind="clip", start="The nightly glass of wine", end="the hardest", src=[f"{ST}/p7687087.mp4@5.0"], note="red wine pouring into a glass"),
 dict(id="G15", kind="scene", scene="fact", start="Two glasses a night", end="you get abs", photo=f"{PH}/wine.jpg",
      eyebrow=["2 GLASSES A NIGHT", "Two glasses a night"], headline=[["1,700", "somewhere around"], ["CALORIES", "calories plus"]],
      detail=["a week + 7 nights of bad sleep.", "7 nights"], sweep="forever", push=1.06, drift=-8),
 dict(id="G16", kind="lt", start="If you are counting the Wednesday", end="times you noticed", topic="BE HONEST",
      point="The Wednesday Beers COUNT.", parts=[["The Wednesday Beers COUNT.", "Wednesday beers"]]),
 dict(id="T5", kind="title", start="Rule number 5", dur=2.4, step=5, headline="Stop 3 Hours Before Bed"),
 dict(id="G17", kind="lt", start="This is the sleep protection", end="takes from you", topic="THE SLEEP PROTECTION RULE",
      point="Last Drink 3 HOURS Before Bed.", parts=[["Last Drink 3 HOURS Before Bed.", "This is the sleep"]]),
 dict(id="C13", kind="clip", start="You wake up functional", end="falling apart", src=[f"{ST}/p5983685.mp4@6.0"], note="man waking up and stretching in a bright bedroom"),
 dict(id="C14", kind="clip", start="Drink water in between", end="It does not", src=[f"{ST}/p4250584.mp4@2.5"], note="water poured into a glass"),
 dict(id="T6", kind="title", start="Rule number six. The next morning run", dur=2.4, step=6, headline="Run Your Normal Fast"),
 dict(id="G18", kind="lt", start="This is where most guys", end="feeling like hell", topic="RULE 6",
      point="Most Guys Lose The NEXT MORNING.", parts=[["Most Guys Lose", "This is where most"], ["The NEXT MORNING.", "The next morning you"]]),
 dict(id="C15", kind="clip", start="you decide last night", end="greasy breakfast", tail=0.3, src=[f"{ST}/p8526489.mp4@10.0", f"{ST}/p6529457.mp4@1.0"],
      note="man asleep on a sofa beside a table of empty bottles, then a diner breakfast of pancakes and hash browns (hard cut)"),
 dict(id="G19", kind="lt", start="One bad night is completely", end="weekend is not", topic="CONTAIN THE DAMAGE",
      point="One Bad Night Is RECOVERABLE.", parts=[["One Bad Night Is RECOVERABLE.", "One bad night"]]),
 dict(id="C16", kind="clip", start="Wake up, drink your coffee", end="to one night", src=[f"{ST}/p5694285.mp4@4.0"], note="coffee poured from a moka pot"),
 # ---------------- the honest truth
 dict(id="G20", kind="lt", start="If you are actively cutting", end="slows you down", topic="STILL CUTTING?",
      point="Drink As LITTLE As Possible.", parts=[["Drink As LITTLE As Possible.", "the real answer"]]),
 dict(id="G21", kind="lt", start="Once you are maintaining", end="keeping your abs", topic="MAINTAINING?",
      point="Moderate Drinking Inside The Rules WORKS.", parts=[["Moderate Drinking", "moderate drinking"], ["Inside The Rules WORKS.", "completely compatible"]]),
 dict(id="G22", kind="l3", start="I only drink 1 or 2 days", end="on this list", heading="What I Do",
      points=["1 or 2 days a week", "No liquor", "All 6 rules"], reveal=["I only drink", "don't drink liquor", "follow all"]),
 dict(id="P01", kind="scene", scene="portraits_codex", start="And that's how I can maintain", end="nights per week",
      photos=["studio-white-23", "studio-blue-173", "studio-blue-240"], label="Real pictures of me. Not AI-generated.",
      note="the three-photo slate Dan picked on RO-16 (09-30), reused"),
 dict(id="G23", kind="lt", start="I used to drink 5", end="closer to 10", topic="WHAT I USED TO DRINK",
      point="5 To 10 Drinks A Week. Mostly 10.", parts=[["5 To 10 Drinks A Week.", "I used to drink"], ["Mostly 10.", "closer to 10"]]),
 dict(id="C17", kind="clip", start="then a blowout party night", end="4 to six", src=[f"{ST}/p9003382.mp4@0.5"], note="crowd at a club in front of a DJ"),
 dict(id="G24", kind="lt", start="Now when I go out", end="missing anything", topic="WHAT I DO NOW",
      point="1 Or 2 Drinks, And I'm DONE.", parts=[["1 Or 2 Drinks,", "I have one or two"], ["And I'm DONE.", "then I'm done"]]),
 # ---------------- wrap
 dict(id="G25", kind="lt", start="Taking Zepbound massively", end="under control", topic="WHAT HELPED ME",
      point="My Desire To Drink DROPPED.", parts=[["My Desire To Drink DROPPED.", "massively reduced"]]),
 dict(id="G26", kind="scene", scene="recap", start="Fast first, count it", end="become a weekend", tail=0.5, eyebrow="THE 6 RULES",
      headline="Drink And Keep Your Abs",
      items=["Eat first, then drink", "Count the calories", "No sugary mixers", "1 or 2 nights a week", "Stop 3 hours before bed", "Run your normal fast"]),
]
