'use strict';
const $=id=>document.getElementById(id), el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
let state=null, busy=false, conflict=false, current=null, baseDraft='', pendingClose=null, dragging=null, panel=null;
const activeLists=()=>state.lists.filter(l=>!l.archived), getCard=()=>state.cards.find(c=>c.id===current);
const dateText=s=>new Date(s).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});
function notice(text){$('notice').textContent=text;$('dialog-notice').textContent=text;$('panel-notice').textContent=text;}
function button(text,fn,cls='btn'){const b=el('button',cls,text);b.type='button';b.addEventListener('click',fn);return b;}
function formDraft(){return {title:$('card-title').value,description:$('card-description').value,dueDate:$('card-due').value,labels:[...$('card-labels').children].map(row=>({name:row.querySelector('input').value,color:row.querySelector('select').value}))};}
function dirty(){return current&&(JSON.stringify(formDraft())!==baseDraft||$('check-text').value.trim()||$('comment-text').value.trim());}
function busySet(value){busy=value;document.querySelectorAll('button').forEach(b=>b.disabled=value||(!state&&b.id!=='refresh'));$('save-state').textContent=value?'Saving…':state?`Saved · version ${state.version}`:'Loading…';}
async function response(res){if(res.status===401){notice('Your sign-in expired. Open sign-in in another tab, then return and Refresh. Your current draft is still here.');for(const id of ['notice','dialog-notice','panel-notice']){const a=el('a','',' Sign in');a.href='/workboard-login';a.target='_blank';a.rel='noopener';$(id).append(a);}throw new Error('');}let data;try{data=await res.json();}catch{throw new Error('The server did not return the board. Please retry.');}if(!res.ok){if(res.status===409)conflict=true;throw new Error(data.error||'Could not save. Please retry.');}return data;}
async function load(){if(busy)return;busySet(true);try{state=await response(await fetch('/api/workboard/state',{cache:'no-store'}));const wasConflict=conflict;conflict=false;render();if(current)renderCardParts();notice(wasConflict?'Latest board loaded. Your open draft was kept. Compare it with the latest saved values before saving.':'');if(wasConflict&&current){const c=getCard();if(c){const box=el('div','comment',`Latest saved title: ${c.title}\nDescription: ${c.description}\nDue date: ${c.dueDate||'None'}\nLabels: ${c.labels.map(l=>l.name+' | '+l.color).join(', ')||'None'}`);$('card-activity').prepend(box);}}}catch(e){if(e.message)notice(e.message);}finally{busySet(false);}}
async function change(action,payload,options={}){if(busy)return false;if(conflict){notice('Refresh to load changes from the other tab first. Your draft is kept.');return false;}busySet(true);try{state=await response(await fetch('/api/workboard/change',{method:'POST',headers:{'Content-Type':'application/json','X-Workboard-Action':'change'},body:JSON.stringify({version:state.version,action,payload})}));render();if(current)renderCardParts();notice('');if(options.after)options.after();return true;}catch(e){if(e.message)notice(e.message);return false;}finally{busySet(false);}}
function tone(l){return l.tone||'';}
function render(){
  const q=$('search').value.trim().toLowerCase(), board=$('board');board.replaceChildren();
  activeLists().forEach((l,i)=>{
    const column=el('section','column '+tone(l));column.dataset.listId=l.id;
    const phase=el('div','phase',String(i+1).padStart(2,'0')+' · '+(l.name.toLowerCase().includes('queue')?'Queue':l.name.toLowerCase().includes('review')?'Review':l.name==='Done'?'Close':'Work'));
    const head=el('div','column-head');head.draggable=!q;head.dataset.dragList=l.id;
    const title=el('div','column-title',l.name),cards=state.cards.filter(c=>c.listId===l.id&&!c.archived&&[c.title,c.description,...c.labels.map(l=>l.name)].join(' ').toLowerCase().includes(q));
    title.append(el('span','count',cards.length));const menu=button('···',()=>listPanel(l));menu.setAttribute('aria-label','List menu: '+l.name);head.append(title,menu);
    column.append(phase,head,el('p','column-note',l.name.includes('queue')?'Top card is next':l.name.includes('in progress')?'Keep active work small':l.name.includes('review')?'Review and leave a decision':l.name==='Done'?'Approved work; archive regularly':'Capture selectively'));
    const stack=el('div','cards');stack.dataset.dropList=l.id;
    cards.forEach(c=>{const card=el('article','card');card.draggable=!q;card.tabIndex=0;card.setAttribute('role','button');card.setAttribute('aria-label','Open card: '+c.title);card.dataset.cardId=c.id;const tags=el('div','card-tags');c.labels.forEach(t=>tags.append(el('span','tag '+t.color,t.name)));if(c.labels.length)card.append(tags);card.append(el('h3','',c.title));if(c.description)card.append(el('p','',c.description.slice(0,160)+(c.description.length>160?'…':'')));const foot=el('div','card-footer');if(c.checklist.length)foot.append(el('span','',`✓ ${c.checklist.filter(x=>x.done).length}/${c.checklist.length}`));if(c.dueDate)foot.append(el('span',c.dueDate<new Date().toLocaleDateString('en-CA')?'overdue':'','Due '+c.dueDate));if(c.comments.length)foot.append(el('span','',`◌ ${c.comments.length}`));if(c.attachments.length)foot.append(el('span','',`↗ ${c.attachments.length}`));if(foot.children.length)card.append(foot);card.addEventListener('click',()=>openCard(c.id));card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openCard(c.id);}});stack.append(card);});
    if(!cards.length)stack.append(el('div','empty',q?'No matching cards':'Space for the next task'));
    column.append(stack,button('＋ Add card',()=>newCard(l),'add'));board.append(column);
  });
  if(!activeLists().length)board.append(button('＋ Create a list',newList,'btn new-list'));
}
function showPanel(title,content){panel=content;$('panel-heading').textContent=title;$('panel-body').replaceChildren();content($('panel-body'));$('panel-dialog').showModal();}
function newList(){showPanel('Add list',body=>{const f=el('form'),label=el('label','','List name'),input=el('input');input.required=true;input.maxLength=100;input.setAttribute('aria-label','List name');label.append(input);const b=el('button','btn primary','Create list');f.append(label,b);f.onsubmit=async e=>{e.preventDefault();if(await change('list.create',{name:input.value}))$('panel-dialog').close();};body.append(f);});}
function newCard(l){showPanel('Add card to '+l.name,body=>{const f=el('form'),label=el('label','','Card title'),input=el('input');input.required=true;input.maxLength=200;input.setAttribute('aria-label','New card title');label.append(input);f.append(label,el('button','btn primary','Create card'));f.onsubmit=async e=>{e.preventDefault();if(await change('card.create',{listId:l.id,title:input.value})){const id=state.target;$('panel-dialog').close();openCard(id);}};body.append(f);});}
function listPanel(l){showPanel(l.name,body=>{const f=el('form'),label=el('label','','List name'),input=el('input');input.value=l.name;input.maxLength=100;input.required=true;input.setAttribute('aria-label','List name');label.append(input);f.append(label,el('button','btn','Rename list'));f.onsubmit=async e=>{e.preventDefault();if(await change('list.update',{id:l.id,name:input.value}))$('panel-dialog').close();};body.append(f);const label2=el('label','','Position'),select=el('select');select.setAttribute('aria-label','List position');activeLists().forEach((x,i)=>select.append(new Option(String(i+1),String(i))));select.value=String(activeLists().findIndex(x=>x.id===l.id));label2.append(select);body.append(label2,button('Move list',async()=>{if(await change('list.move',{id:l.id,index:Number(select.value)}))$('panel-dialog').close();}),button('Archive list',async()=>{if(await change('list.archive',{id:l.id}))$('panel-dialog').close();},'btn danger'),el('p','muted','Archiving hides this list and its cards. Restore it from Archive.'));});}
function openCard(id){current=id;const c=getCard();if(!c)return;$('check-text').value='';$('comment-text').value='';$('file-input').value='';setForm(c);renderCardParts();$('card-dialog').showModal();if(location.hash!=='#card='+id)history.pushState({card:id},'', '#card='+id);}
function setForm(c){$('card-title').value=c.title;$('card-description').value=c.description;$('card-due').value=c.dueDate;$('card-labels').replaceChildren();c.labels.forEach(addLabel);baseDraft=JSON.stringify(formDraft());$('draft-state').textContent='Saved';}
function renderCardParts(){
  const c=getCard();if(!c)return;const l=state.lists.find(l=>l.id===c.listId);$('card-location').textContent=l.name;$('card-meta').textContent='Created '+dateText(c.createdAt)+' · Updated '+dateText(c.updatedAt);
  $('check-count').textContent=`${c.checklist.filter(x=>x.done).length}/${c.checklist.length}`;$('checklist').replaceChildren();
  c.checklist.forEach(item=>{const row=el('div','check-row'),check=el('input');check.type='checkbox';check.checked=item.done;check.setAttribute('aria-label',item.text);check.onchange=async()=>{if(!await change('check.update',{id:c.id,itemId:item.id,done:check.checked,text:item.text}))check.checked=item.done;};row.append(check,el('span','',item.text),button('Edit',()=>{showPanel('Edit checklist item',body=>{const f=el('form'),input=el('input');input.value=item.text;input.maxLength=500;input.required=true;input.setAttribute('aria-label','Checklist item text');f.append(input,el('button','btn','Save item'));f.onsubmit=async e=>{e.preventDefault();if(await change('check.update',{id:c.id,itemId:item.id,text:input.value,done:item.done}))$('panel-dialog').close();};body.append(f);});}),button('×',()=>change('check.delete',{id:c.id,itemId:item.id})));row.lastChild.setAttribute('aria-label','Delete checklist item: '+item.text);$('checklist').append(row);});
  $('attachments').replaceChildren();c.attachments.forEach(a=>{const row=el('div','attachment-row'),link=el('a','',a.name);link.href='/api/workboard/files/'+a.id;link.download=a.name;row.append(link,el('small','',Math.ceil(a.size/1024)+' KB'),button('Remove',()=>change('attachment.remove',{id:c.id,attachmentId:a.id})));$('attachments').append(row);});
  $('comments').replaceChildren();c.comments.forEach(x=>{const row=el('div','comment',x.text);row.append(el('small','','Dan · '+dateText(x.createdAt)));$('comments').append(row);});
  $('move-list').replaceChildren(...activeLists().map(l=>new Option(l.name,l.id)));$('move-list').value=c.listId;positions();
  $('card-activity').replaceChildren();state.activity.filter(a=>a.cardId===c.id).slice(0,30).forEach(a=>$('card-activity').append(eventNode(a)));
}
function positions(){const c=getCard(),listId=$('move-list').value,others=state.cards.filter(x=>x.listId===listId&&!x.archived&&x.id!==current);$('move-position').replaceChildren(...Array.from({length:others.length+1},(_,i)=>new Option(String(i+1),String(i))));const currentIndex=state.cards.filter(x=>x.listId===listId&&!x.archived).findIndex(x=>x.id===c.id);$('move-position').value=String(currentIndex<0?others.length:currentIndex);}
function closeCard(force=false){if(busy&&!force)return;if(dirty()&&!force){pendingClose=()=>closeCard(true);$('confirm-dialog').showModal();return;}$('card-dialog').close();current=null;baseDraft='';if(location.hash)history.replaceState(null,'',location.pathname);}
function eventNode(a){const n=el('div','event',a.text);n.append(el('small','',dateText(a.at)));return n;}
function archivePanel(){showPanel('Archive',body=>{body.append(el('h3','','Lists'));state.lists.filter(l=>l.archived).forEach(l=>{const row=el('div','archive-row');row.append(el('span','',l.name),button('Restore list',async()=>{if(await change('list.restore',{id:l.id}))archivePanelRefresh();}));body.append(row);});body.append(el('h3','','Cards'));state.cards.filter(c=>c.archived||state.lists.find(l=>l.id===c.listId)?.archived).forEach(c=>{const row=el('div','archive-row'),l=state.lists.find(l=>l.id===c.listId);row.append(el('span','',c.title+' · '+l.name));if(l.archived)row.append(el('small','','Restore list first'));else row.append(button('Restore card',async()=>{if(await change('card.restore',{id:c.id}))archivePanelRefresh();}));body.append(row);});if(!state.lists.some(l=>l.archived)&&!state.cards.some(c=>c.archived))body.append(el('p','muted','Nothing archived.'));});}
function archivePanelRefresh(){$('panel-dialog').close();archivePanel();}
$('search').oninput=()=>state&&render();$('refresh').onclick=load;$('card-refresh').onclick=load;$('panel-refresh').onclick=load;$('new-list').onclick=newList;$('archive').onclick=archivePanel;$('activity').onclick=()=>showPanel('Activity',body=>{body.append(el('p','muted','Most recent 500 board changes.'));state.activity.forEach(a=>body.append(eventNode(a)));if(!state.activity.length)body.append(el('p','','No changes yet.'));});$('panel-close').onclick=()=>$('panel-dialog').close();
$('move-list').onchange=positions;$('move-card').onclick=()=>change('card.move',{id:current,listId:$('move-list').value,index:Number($('move-position').value)});
$('card-form').onsubmit=async e=>{e.preventDefault();const d=formDraft();if(await change('card.update',{id:current,...d}))setForm(getCard());};
['card-title','card-description','card-due','card-labels'].forEach(id=>$(id).oninput=()=>$('draft-state').textContent=dirty()?'Unsaved changes':'Saved');
function addLabel(value={name:'',color:'slate'}){const row=el('div','label-row'),input=el('input'),select=el('select');input.value=value.name;input.maxLength=40;input.required=true;input.placeholder='Label name';input.setAttribute('aria-label','Label name');select.setAttribute('aria-label','Label color');['slate','green','amber','blue','rose','purple'].forEach(c=>select.append(new Option(c[0].toUpperCase()+c.slice(1),c)));select.value=value.color;row.append(input,select,button('×',()=>{row.remove();$('draft-state').textContent='Unsaved changes';}));row.lastChild.setAttribute('aria-label','Remove label');$('card-labels').append(row);}
$('label-add').onclick=()=>{if($('card-labels').children.length>=12)return notice('Use at most 12 labels.');addLabel();$('card-labels').lastChild.querySelector('input').focus();$('draft-state').textContent='Unsaved changes';};
$('check-text').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();$('check-add').click();}});
$('check-add').onclick=async()=>{if(await change('check.add',{id:current,text:$('check-text').value}))$('check-text').value='';};$('comment-add').onclick=async()=>{if(await change('comment.add',{id:current,text:$('comment-text').value}))$('comment-text').value='';};
$('archive-card').onclick=()=>{if(dirty()){pendingClose=async()=>{if(await change('card.archive',{id:current}))closeCard(true);};$('confirm-dialog').showModal();}else change('card.archive',{id:current},{after:()=>closeCard(true)});};
document.querySelectorAll('.close').forEach(b=>b.onclick=()=>closeCard());$('card-dialog').addEventListener('cancel',e=>{e.preventDefault();closeCard();});$('keep-editing').onclick=()=>{$('confirm-dialog').close();pendingClose=null;};$('discard').onclick=()=>{$('confirm-dialog').close();const fn=pendingClose;pendingClose=null;fn?.();};
window.addEventListener('beforeunload',e=>{if(dirty()||busy){e.preventDefault();e.returnValue='';}});window.addEventListener('popstate',()=>{if(current)closeCard();});
$('file-input').onchange=async()=>{const file=$('file-input').files[0];if(!file||busy)return;if(conflict){notice('Refresh the board before uploading.');return;}if(file.size>8*1024*1024){notice('Files may be up to 8 MB.');return;}const ext=file.name.split('.').pop().toLowerCase(),mime=['txt','md','csv','srt'].includes(ext)?'text/plain':file.type;busySet(true);try{state=await response(await fetch('/api/workboard/cards/'+current+'/attachments',{method:'POST',headers:{'Content-Type':mime||'application/octet-stream','X-Workboard-Action':'change','X-Board-Version':String(state.version),'X-File-Name':encodeURIComponent(file.name)},body:file}));render();renderCardParts();notice('File attached.');$('file-input').value='';}catch(e){if(e.message)notice(e.message);}finally{busySet(false);}};
document.addEventListener('dragstart',e=>{if(busy||$('search').value.trim())return e.preventDefault();const c=e.target.closest('[data-card-id]'),l=e.target.closest('[data-drag-list]');dragging=c?{type:'card',id:c.dataset.cardId}:l?{type:'list',id:l.dataset.dragList}:null;if(!dragging)return;e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',dragging.id);e.target.classList.add('dragging');});
document.addEventListener('dragover',e=>{if(!dragging)return;const target=e.target.closest(dragging.type==='card'?'[data-drop-list]':'[data-list-id]');if(target){e.preventDefault();document.querySelectorAll('.drop-target').forEach(n=>n.classList.remove('drop-target'));target.classList.add('drop-target');}});
document.addEventListener('drop',e=>{if(!dragging)return;const d=dragging;dragging=null;e.preventDefault();document.querySelectorAll('.drop-target,.dragging').forEach(n=>n.classList.remove('drop-target','dragging'));if(d.type==='list'){const dest=e.target.closest('[data-list-id]');if(!dest)return;const others=activeLists().filter(l=>l.id!==d.id);let index=others.findIndex(l=>l.id===dest.dataset.listId);if(index<0)return;if(e.clientX>dest.getBoundingClientRect().x+dest.getBoundingClientRect().width/2)index++;change('list.move',{id:d.id,index});}else{const stack=e.target.closest('[data-drop-list]');if(!stack)return;const cards=[...stack.querySelectorAll('[data-card-id]')].filter(n=>n.dataset.cardId!==d.id);let index=cards.findIndex(n=>e.clientY<n.getBoundingClientRect().y+n.getBoundingClientRect().height/2);if(index<0)index=cards.length;change('card.move',{id:d.id,listId:stack.dataset.dropList,index});}});
document.addEventListener('dragend',()=>{dragging=null;document.querySelectorAll('.drop-target,.dragging').forEach(n=>n.classList.remove('drop-target','dragging'));});
load().then(()=>{const id=location.hash.replace('#card=','');if(state?.cards.some(c=>c.id===id&&!c.archived))openCard(id);});
