# (key, SOURCE seconds, eyebrow, title)
CHIPS = [
 ("title",     138.0, "ABS BY AI // DAN ROSE",        "MY FIRST SPRAY TAN"),
 ("why",       196.0, "THE PROBLEM",                  "CAMERAS FLATTEN YOU"),
 ("contrast",  249.0, "THE REAL REASON",              "DEFINITION IS CONTRAST"),
 ("askai",     308.0, "HOW I FOUND A STUDIO",         "I ASKED MY AI"),
 ("cost",      370.0, "WHAT I PAID",                  "$80 BASE + $20 CONTOURING"),
 ("diy",       416.0, "CHEAPER OPTIONS",              "AEROSOL + TANNING WIPES"),
 ("appt",      491.0, "THE APPOINTMENT",              "10 MINUTES, DOWN TO BRIEFS"),
 ("dry",       586.0, "AFTERCARE 01",                 "NO SHOWER FOR 8 HOURS"),
 ("shower",    641.0, "AFTERCARE 02",                 "NO SOAP, NO SCRUBBING"),
 ("care",      692.0, "AFTERCARE 03",                 "NO WASHCLOTHS, NO EXFOLIANTS"),
 ("lasts",     730.0, "HOW LONG IT LASTS",            "ABOUT 7 DAYS"),
 ("water",     793.0, "BIGGEST DOWNSIDE",             "WATER WEARS IT OFF"),
 ("compare",   860.0, "JUDGE FOR YOURSELF",           "BEFORE VS AFTER"),
 ("pro1",      927.0, "PRO 01",                       "NO SUN DAMAGE"),
 ("pro2",     1084.0, "PRO 02",                       "IF YOU CANNOT TAN AT ALL"),
 ("con1",     1174.0, "CON 01",                       "$50-$100 EVERY TIME"),
 ("con2",     1240.0, "CON 02",                       "DIY IS UNEVEN"),
 ("con3",     1258.0, "CON 03",                       "A CHEAP TAN LOOKS ORANGE"),
 ("con4",     1290.0, "CON 04",                       "IT WEARS OFF IN A WEEK"),
 ("who1",     1327.0, "WHO SHOULD",                   "ANYONE VERY PALE"),
 ("who2",     1374.0, "WHO SHOULD NOT",               "ANYONE ON A TIGHT BUDGET"),
 ("shoot1",   1517.0, "SHOOT DAY 01",                 "GOOD LIGHT, NEVER NOON"),
 ("shoot2",   1546.0, "SHOOT DAY 02",                 "GET A PUMP FIRST"),
 ("shoot3",   1558.0, "SHOOT DAY 03",                 "SHOOT FASTED"),
 ("shoot4",   1572.0, "SHOOT DAY 04",                 "PRACTICE YOUR POSING"),
 ("cta",      1781.0, "GET STARTED FREE",             "ABSBYAI.COM"),
]
