# (key, SOURCE seconds, eyebrow, title)
CHIPS = [
 ("title",     40.0,  "ABS BY AI // DAN ROSE",   "MY FULL SUPPLEMENT STACK"),
 ("decide",   117.0,  "HOW TO DECIDE",           "NOT FROM INFLUENCERS"),
 ("ai",       161.0,  "THE FIX",                 "LET AI READ THE RESEARCH"),
 ("ag1",      370.0,  "ON WAKING 01",            "ATHLETIC GREENS"),
 ("vitd",     529.0,  "ON WAKING 02",            "VITAMIN D"),
 ("food",     618.0,  "POST-WORKOUT 01",         "FOOD FIRST, THEN PILLS"),
 ("fish",     688.0,  "POST-WORKOUT 02",         "FISH OIL"),
 ("curc",     784.0,  "POST-WORKOUT 03",         "CURCUMIN"),
 ("ginger",   861.0,  "POST-WORKOUT 04",         "GINGER"),
 ("gluco",    905.0,  "POST-WORKOUT 05",         "GLUCOSAMINE CHONDROITIN"),
 ("skin",    1002.0,  "FOR YOUR SKIN",           "B6 - ZINC - DIM"),
 ("test",    1072.0,  "POST-WORKOUT 06",         "TESTOSTERONE BOOSTER"),
 ("aminos",  1140.0,  "THE DRINK 01",            "AMINOS (OR WHEY)"),
 ("mag",     1245.0,  "THE DRINK 02",            "MAGNESIUM"),
 ("coll",    1276.0,  "THE DRINK 03",            "COLLAGEN"),
 ("elec",    1320.0,  "THE DRINK 04",            "ELECTROLYTES"),
 ("sleep",   1350.0,  "BEFORE BED",              "DEEP SLEEP COMPLEX"),
 ("creat",   1401.0,  "WHAT I SKIP",             "CREATINE"),
 ("mistake", 1492.0,  "BIGGEST MISTAKE",         "BUYING IT ALL AT ONCE"),
 ("big3",    1556.0,  "START HERE",              "FISH OIL - VITAMIN D - MAGNESIUM"),
 ("step2",   1600.0,  "STEP 02",                 "ADD MUSCLE SUPPORT"),
 ("step3",   1637.0,  "STEP 03",                 "ADD GREENS"),
 ("step4",   1683.0,  "STEP 04",                 "ADD SKIN SUPPORT"),
 ("step5",   1724.0,  "STEP 05",                 "ADD TEST BOOSTER LAST"),
 ("never",   1742.0,  "NEVER BUY",               "PRE-WORKOUTS + FAT BURNERS"),
 ("fivepct", 1874.0,  "KEEP IT IN PERSPECTIVE",  "SUPPLEMENTS ARE 5% OF RESULTS"),
 ("cta",     2186.0,  "GET STARTED FREE",        "ABSBYAI.COM"),
]
