"""RO-11 visual plan. Every item is anchored to the words Dan says (phrase -> output time via words_out.json).
Kinds built from the approved HyperFrames templates (hyperframes/from_plan.py): lt (Motivation lower third, parts land on
their words), scene/fact (before / fact card), l3 (3A side list, items land on their words), cycle (4-step loop card).
Kinds that stay softblue.py: title (full-screen way card), scene/recap, phone (app demo beside Dan). clip = full-frame
cutaway (Pexels / library), hard cuts. start = phrase whose first word starts the item; end = phrase whose last word
ends it (or dur). Inside a template item every time is a phrase too (resolved by from_plan.py)."""
LIB = "/Volumes/Extreme/_asset_library_stage/Abs By AI - Video Asset Library"
ST = "/Volumes/Extreme/_edit_work/ro11/stock"
PH = "/Volumes/Extreme/_edit_work/ro11/assets"
PLAN = [
 # ---------------- hook: AI opener over his first line (frames shown for approval; motion not generated)
 dict(id="A01", kind="ai", start="can still gain fat", end="too many calories", tail=0.3,
      note="AI opener, concept A: heavy man steps on the scale after eating clean, sees the number, grabs his belly"),
 dict(id="G01", kind="lt", start="Even if you're eating", end="screwing other things up", topic="CALORIES AREN'T EVERYTHING",
      point="In A Deficit, You Can Still KEEP Your Belly Fat.",
      parts=[["In A Deficit,", "Even if you're eating"], ["You Can Still KEEP Your Belly Fat.", "you might still hold"]]),
 # ---------------- factor 1: sleep
 dict(id="T1", kind="title", start="Number one is sleep", dur=2.4, step=1, headline="Sleep"),
 dict(id="C01", kind="clip", start="For two weeks, they slept", end="hours per night", src=[f"{ST}/p7556225.mp4@2.0"], note="man asleep in bed"),
 dict(id="C02", kind="clip", start="For another two weeks", end="they only got", tail=1.0, src=[f"{ST}/p6944072.mp4@6.0"], note="man awake on the edge of his bed at night"),
 dict(id="G02", kind="scene", scene="fact", start="When they were short on sleep", end="more muscle", photo=f"{PH}/sleep.jpg",
      eyebrow=["U. OF CHICAGO, 2010", "When they were short"], headline=[["55% LESS", "55"], ["FAT", "less fat"]], count={"value": "55", "from": 0, "dur": 0.55},
      detail=["lost, and 60% MORE muscle lost.", "and they lost"], sweep="more muscle", push=1.06, drift=-8),
 dict(id="G03", kind="l3", start="So here's what I do", end="already working for", heading="How I Sleep",
      points=["Bedroom at 63 degrees", "Same bedtime every night", "AI sleep coach every morning", "Glycine every night"],
      reveal=["I keep my bedroom", "consistent bedtime", "AI sleep coach", "glycine"]),
 # ---------------- factor 2: alcohol
 dict(id="T2", kind="title", start="let's talk about the next one", dur=2.4, step=2, headline="Alcohol"),
 dict(id="C03", kind="clip", start="Your body treats alcohol", end="burns anything else", src=[f"{ST}/p10317805.mp4@1.0"], note="whiskey glass on a bar"),
 dict(id="G04", kind="scene", scene="fact", start="In one study, they gave men", end="next several hours", photo=f"{PH}/drinks.jpg",
      eyebrow=["1999 STUDY", "In one study"], headline=[["73% LESS", "73"]], count={"value": "73", "from": 0, "dur": 0.55},
      detail=["fat burning, hours after 2 drinks.", "for the next"], sweep="several hours", push=1.06, drift=-8),
 dict(id="C04", kind="clip", start="Most guys aren't stopping", end="Saturday night", tail=0.35, src=[f"{ST}/p5847850.mp4@1.0"], note="friends clinking beer mugs"),
 dict(id="G05", kind="lt", start="The short version is", end="at the same calories", topic="THE SHORT VERSION",
      point="Less Alcohol = FASTER Belly Fat Loss.",
      parts=[["Less Alcohol =", "the less you drink"], ["FASTER Belly Fat Loss.", "the faster"]]),
 # ---------------- factor 3: hormones
 dict(id="T3", kind="title", start="Hormones. So let me", dur=2.4, step=3, headline="Hormones"),
 dict(id="G06", kind="lt", start="When your testosterone is low", end="eating the same calories", topic="LOW TESTOSTERONE",
      point="More Belly Fat, LESS MUSCLE. Same Calories.",
      parts=[["More Belly Fat,", "stores more fat"], ["LESS MUSCLE.", "holds on to less"], ["Same Calories.", "even if you're eating"]]),
 dict(id="C05", kind="clip", start="When you're stressed out", end="and high cortisol", end_at_start=True, src=[f"{ST}/p6290471.mp4@2.0"], note="stressed man at a desk, head in hand"),
 dict(id="G07", kind="lt", start="and high cortisol tells", end="belly specifically", topic="CORTISOL: YOUR STRESS HORMONE",
      point="High Stress Tells Your Body: Store Fat In The BELLY.",
      parts=[["High Stress Tells Your Body:", "high cortisol tells"], ["Store Fat In The BELLY.", "store fat"]]),
 dict(id="C06", kind="clip", start="go get a blood test", end="instead of just guessing", src=[f"{ST}/p6036689.mp4@2.0"], note="blood draw, arm close-up"),
 dict(id="G08", kind="lt", start="The normal range that doctors", end="don't feel the same", topic="THE NORMAL RANGE IS WIDE",
      point="300 And 900 Are Both Called NORMAL.",
      parts=[["300 And 900", "A guy at"], ["Are Both Called NORMAL.", "both called normal"]]),
 # ---------------- factor 4: meal timing
 dict(id="T4", kind="title", start="Okay, the next factor is timing", dur=2.4, step=4, headline="Meal Timing"),
 dict(id="C07", kind="clip", start="eating a big meal right before bed", end="hurts your sleep", tail=0.4, src=[f"{ST}/p9902350.mp4@8.0"], note="man eating on his bed at night"),
 dict(id="G09", kind="scene", scene="fact", start="When they ate late", end="calories per day", photo=f"{PH}/latemeal.jpg",
      eyebrow=["HARVARD, 2022", "When they ate late"], headline=[["2X", "twice as likely"], ["AS HUNGRY", "to be hungry"]],
      detail=["and 60 fewer calories burned.", "and they burned"], sweep="calories per day", push=1.06, drift=-8),
 dict(id="G10", kind="lt", start="So I would stop eating", end="go to bed", topic="MY RULE",
      point="Stop Eating 3 HOURS Before Bed.", parts=[["Stop Eating 3 HOURS Before Bed.", "stop eating about"]]),
 dict(id="G11", kind="scene", scene="fact", start="After two months", end="without even trying", photo=f"{PH}/plate.jpg",
      eyebrow=["U. OF ILLINOIS, 2020", "After two months"], headline=[["550 FEWER", "550"]], count={"value": "550", "from": 0, "dur": 0.6},
      detail=["calories a day, with no counting.", "fewer calories"], sweep="even trying", push=1.06, drift=-8),
 dict(id="G12", kind="lt", start="The fasting group ate about", end="calorie counters", topic="1-YEAR STUDY",
      point="Fasting Until Noon MATCHED Counting Calories.",
      parts=[["Fasting Until Noon", "The fasting group"], ["MATCHED Counting Calories.", "They did just as well"]]),
 # ---------------- factor 5: protein
 dict(id="T5", kind="title", start="is your macronutrients", dur=2.4, step=5, headline="Protein"),
 dict(id="G13", kind="lt", start="your body burns about", end="With carbs", tail=2.3, topic="CALORIES BURNED DIGESTING IT",
      point="Protein: 20-30%. Carbs: 5-10%.",
      parts=[["Protein: 20-30%.", "your body burns"], ["Carbs: 5-10%.", "With carbs"]]),
 dict(id="C08", kind="clip", start="calories of chicken", end="calories of bread", tail=0.3, src=[f"{ST}/p38757135.mp4@1.0", f"{ST}/p5116397.mp4@3.0"],
      note="chicken breasts in a pan, then slices of bread on a plate"),
 dict(id="G14", kind="scene", scene="fact", start="The high protein group lost", end="pounds of muscle", photo=f"{PH}/lift.jpg",
      eyebrow=["McMASTER, 2016", "The high protein group"], headline=[["+2.5 lb", "they gained"], ["MUSCLE", "of muscle"]],
      detail=["plus 10.5 lb of fat lost.", "of muscle"], sweep="of muscle", push=1.06, drift=-8),
 dict(id="C09", kind="clip", start="So every meal you eat needs", end="meat, fish or eggs", tail=0.3, src=["B0287@4.0"], note="eggs and bacon in a skillet (library B0287)"),
 dict(id="G15", kind="lt", start="Get your protein in first", end="you have left", topic="EVERY MEAL",
      point="Protein FIRST. Then Carbs With What's Left.",
      parts=[["Protein FIRST.", "Get your protein"], ["Then Carbs With What's Left.", "then fit your carbs"]]),
 # ---------------- factor 6: exercise
 dict(id="T6", kind="title", start="is exercise but not", dur=2.4, step=6, headline="Exercise"),
 dict(id="C10", kind="clip", start="minute jog burns", end="one protein bar", tail=0.3, src=["B0098@1.0"], note="man jogging in a park (library B0098)"),
 dict(id="G16", kind="lt", start="Based on the math", end="they only lost about", tail=1.1, topic="6 MONTHS OF CARDIO",
      point="Should Have Lost 9.5 lb. Lost 3.5.",
      parts=[["Should Have Lost 9.5 lb.", "should have lost"], ["Lost 3.5.", "but they only lost"]]),
 dict(id="G17", kind="scene", scene="fact", start="out of 10 people in that group", end="of food a day", photo=f"{PH}/jog.jpg",
      eyebrow=["PENNINGTON, 2019", "out of 10 people"], headline=[["9 OUT OF 10", "out of 10 people"]],
      detail=["Ate their cardio calories back.", "made up for"], sweep="food a day", push=1.06, drift=-8),
 dict(id="C11", kind="clip", start="Lifting weights is the exercise", end="calories you burn", tail=0.3, src=[f"{ST}/p4259069.mp4@1.0"], note="man curling dumbbells"),
 dict(id="G18", kind="cycle", start="If you lose muscle while", end="all of your muscle", title="The Cycle Of Failure", hue="red", direction="cw",
      boxes=["Lose muscle", "Bulk again", "Gain fat", "Diet again"],
      reveal={"TL": "If you lose muscle", "TR": "bulk again", "BR": "gain fat", "BL": "lose again"},
      close="cycle of failure", pulse="religiously", drift=-12),
 # ---------------- factor 7: daily movement
 dict(id="T7", kind="title", start="And then finally, number", dur=2.4, step=7, headline="Daily Movement"),
 dict(id="G19", kind="scene", scene="fact", start="One person gained", end="same extra calories", photo=f"{PH}/walk.jpg",
      eyebrow=["MAYO CLINIC, 1999", "One person gained"], headline=[["10X", "times difference"], ["DIFFERENCE", "difference from"]],
      detail=["in fat gained. Same extra food.", "from the same"], sweep="extra calories", push=1.06, drift=-8),
 dict(id="C12", kind="clip", start="I mean walking", end="even fidgeting", tail=0.3, src=[f"{ST}/p8550877.mp4@1.0"], note="man walking up outdoor stairs"),
 dict(id="G20", kind="l3", start="So here's what I would do", end="standing desk", heading="Move More",
      points=["8 to 10K steps a day", "Walk after dinner", "Phone calls on your feet", "Standing desk"],
      reveal=["Set a minimum", "Walk after dinner", "take your phone calls", "Work at a standing"]),
 # ---------------- wrap
 dict(id="G21", kind="scene", scene="recap", start="Sleep seven to eight hours in", end="keep your steps up", tail=0.5, eyebrow="THE 7 FACTORS",
      headline="Beyond Calories",
      items=["Sleep 7 to 8 hours", "Cut back on alcohol", "Check your testosterone", "Stop eating 3 hrs before bed",
             "Protein at every meal", "Lift weights", "Keep your steps up"]),
 dict(id="G22", kind="lt", start="If you haven't seen the first video", end="in the description", topic="WATCH NEXT",
      point="Calories: The Reason You're Not Losing Weight",
      parts=[["Calories: The Reason You're Not Losing Weight", "If you haven't seen"]]),
]
