"""RO-07 "Why You MUST Work Out Every Day" visual plan. Every item is anchored to the words Dan says (phrase -> output time
via words_out.json). HyperFrames templates (from_plan.py): lt (Motivation lower third), scene/fact (photo + glass card).
clip = full-frame cutaway, hard cuts. Order of preference kept: Dan's own B-roll (the 7/8 poolside rolls C1490 to C1494 were
shot FOR this video; B#### library cuts for the equipment), existing library clips (A#### AI, B#### stock), then new AI
(three clips, frames first). No side-list cards: both rolls are a centred waist-up medium at 1080p, so a 3A card has no
wall to sit on (RO-06 trap); lists land as lower thirds whose parts come up on the words. No stock source is used twice."""
SHOOT = "/Volumes/Extreme/abs by ai 7:8 Jeff Chagrin shoot/main camera"
RO6 = "/Volumes/Extreme/_edit_work/ro06"
AI = "/Volumes/Extreme/_edit_work/ro07/aiframes"
def br(roll, t): return f"{SHOOT}/{roll}.MP4@{t}"
DAN = dict(people="dan", physique=False)          # real MOVING footage of Dan: no photo label applies
PLAN = [
 # ---------------- hook (first 5 seconds: Dan's own B-roll of the workout, then Dan)
 dict(id="C01", kind="clip", start="Today I'm going to show you why", end="every day", tail=0.1, src=[br("C1491", 3.2), br("C1494", 8.0)], grade=["C1491", "C1494"], **DAN,
      note="OPENER. Dan's own B-roll from this shoot: push-ups by the pool, then the towel row. Real footage, his voice runs underneath"),
 dict(id="G01", kind="lt", start="In today's video", end="twice per week", topic="WORK OUT EVERY DAY",
      point="5 Minutes DAILY Beats 1 Hour Twice A Week.", parts=[["5 Minutes DAILY", "5 minute workout"], ["Beats 1 Hour Twice A Week.", "one hour workout"]]),
 # ---------------- objections
 dict(id="A1", kind="clip", start="I can't even get myself to work out", end="work out every day", tail=0.15, frames=[f"{AI}/A1-start.png", f"{AI}/A1-end.png"], pending=True, label="AI-GENERATED",
      people="other", physique=False, note="NEW AI CLIP (frames for approval): a man on his couch looks over at the packed gym bag by the door, then sinks back into the cushions"),
 dict(id="G02", kind="lt", start="wouldn't that be", end="make yourself do it", topic="COMMON QUESTION",
      point="Is Every Day OVERTRAINING? No.", parts=[["Is Every Day OVERTRAINING?", "wouldn't that be"], ["No.", "the answer is no"]]),
 dict(id="C02", kind="clip", start="if you start off with a short five minute workout", end="capability to do right now", tail=0.1, src=[br("C1493", 8.0)], grade="C1493", **DAN,
      note="Dan's B-roll from this shoot: walking lunges on the yoga mat"),
 dict(id="G03", kind="lt", start="it'll actually be easier", end="twice per week", tail=0.5, topic="KEY POINT",
      point="Short Daily Workouts Are EASIER To Stick To.", parts=[["Short Daily Workouts Are EASIER To Stick To.", "it'll actually be easier"]]),
 dict(id="G04", kind="lt", start="you just have to start", end="five minutes every day", topic="START HERE",
      point="5 Minutes. EVERY Day.", parts=[["5 Minutes.", "five minutes per day"], ["EVERY Day.", "No matter who you are"]]),
 # ---------------- the science objection
 dict(id="C03", kind="clip", start="What I'm telling you right now", end="scientific research", tail=0.2, src=["B0206@2.0"], people="other", physique=False,
      note="library stock: a researcher holds a slide up to a magnifier"),
 dict(id="G05", kind="lt", start="if you put in two hours", end="same results", tail=0.3, topic="WHAT THE STUDIES SAY",
      point="Same Total Sets = Same Results.", parts=[["Same Total Sets", "same amount of total sets"], ["= Same Results.", "essentially the same results"]]),
 dict(id="C04", kind="clip", start="in perfect laboratory conditions", end="that they're doing", tail=0.2, src=["B0394@1.0"], people="other", physique=False,
      note="library stock: lab technicians at their benches"),
 dict(id="G06", kind="lt", start="training beginners", end="laboratory conditions", topic="KEY POINT",
      point="Real Life Is NOT A Laboratory.", parts=[["Real Life Is NOT A Laboratory.", "in the real world"]]),
 dict(id="C05", kind="clip", start="Sometimes things come up", end="emergencies", tail=0.25, src=["A0063@0.3"], label="AI-GENERATED", people="other", physique=False,
      note="library AI clip: a dad gets ready in a morning kitchen while two kids tug at him"),
 dict(id="G07", kind="lt", start="short daily workouts are better", end="rarely", tail=0.6, topic="KEY POINT",
      point="Short And DAILY Beats Long And Rare.", parts=[["Short And DAILY", "short daily workouts"], ["Beats Long And Rare.", "long workouts"]]),
 # ---------------- reason 1
 dict(id="G08", kind="lt", start="Reason number one", end="weightlifting", topic="REASON 1 OF 4",
      point="No Soreness. No DREAD.", parts=[["No Soreness.", "Reason number one"], ["No DREAD.", "when beginners"]]),
 dict(id="A2", kind="clip", start="you are going to be sore", end="experience this", tail=0.1, frames=[f"{AI}/A2-start.png", f"{AI}/A2-end.png"], pending=True, label="AI-GENERATED",
      people="other", physique=False, note="NEW AI CLIP (frames for approval): the morning after a brutal first gym session, a beginner eases himself down a staircase one stiff step at a time, gripping the rail"),
 dict(id="G09", kind="lt", start="And that feeling is going to make you", end="exhausted again", topic="THE REAL PROBLEM",
      point="Your Brain Links Working Out With PAIN.", parts=[["Your Brain Links Working Out With PAIN.", "associate pain"]]),
 dict(id="G10", kind="lt", start="But eventually the discipline", end="start skipping", tail=0.6, topic="KEY POINT",
      point="Discipline Wears Down. Then You SKIP.", parts=[["Discipline Wears Down.", "discipline wears down"], ["Then You SKIP.", "start skipping"]]),
 dict(id="C08", kind="clip", start="if you just start doing five minutes at home", end="tiredness the next day", tail=0.1, src=[br("C1490", 95.0)], grade="C1490", **DAN,
      note="Dan's B-roll from this shoot: bodyweight squats by the pool"),
 dict(id="G11", kind="lt", start="You'll barely feel the soreness", end="so you'll do it again", topic="5 MINUTES A DAY",
      point="Barely Any Soreness. Nothing To DREAD.", parts=[["Barely Any Soreness.", "barely feel"], ["Nothing To DREAD.", "dreading your workout"]]),
 dict(id="G12", kind="lt", start="It doesn't matter how effective", end="if you don't do it", tail=0.8, topic="KEY POINT",
      point="The Best Workout Is The One You Actually DO.", parts=[["The Best Workout Is The One You Actually DO.", "It doesn't matter"]]),
 # ---------------- reason 2
 dict(id="G13", kind="lt", start="here's the next reason", end="twice per week", topic="REASON 2 OF 4",
      point="There Is No DECISION To Make.", parts=[["There Is No DECISION To Make.", "here's the next reason"]]),
 dict(id="C09", kind="clip", start="Maybe somebody in your family", end="go to the hospital", tail=0.15, src=["B0336@2.0"], people="other", physique=False,
      note="library stock: a doctor explains a scan to a patient on a hospital bed"),
 dict(id="C10", kind="clip", start="Maybe there's an emergency at work", end="stay later", tail=0.3, src=["B0494@1.0"], people="other", physique=False,
      note="library stock: a stressed man at his office desk rubs his face"),
 dict(id="C11", kind="clip", start="Maybe you have an injury", end="maybe that", tail=0.1, src=["B0339@1.5"], people="other", physique=False,
      note="library stock: a physical therapist tapes a knee"),
 dict(id="G14", kind="lt", start="If you're making a decision", end="sometimes you won't", tail=0.4, topic="THE TRAP",
      point="If You Have To DECIDE, Sometimes You Won't.", parts=[["If You Have To DECIDE,", "making a decision"], ["Sometimes You Won't.", "sometimes you won't"]]),
 dict(id="G15", kind="lt", start="Mike Tyson once said", end="punched in the face", tail=0.3, topic="MIKE TYSON SAID",
      point="Everyone Has A Plan Until They Get PUNCHED In The Face.", parts=[["Everyone Has A Plan", "everybody has a plan"], ["Until They Get PUNCHED In The Face.", "until you get"]]),
 dict(id="A3", kind="clip", start="And I guarantee you", end="punch you in the face", tail=0.2, frames=[f"{AI}/A3-start.png", f"{AI}/A3-end.png"], pending=True, label="AI-GENERATED",
      people="other", physique=False, note="NEW AI CLIP (frames for approval): a man heads for his front door with a gym bag; a big red boxing glove on a spring pops out of the bag and bops him. Slapstick, like the RO-06 slap"),
 dict(id="G16", kind="lt", start="Something would come up on Thursday", end="the day is missed", tail=0.5, topic="HOW ONE SKIPPED DAY SNOWBALLS",
      point="Thursday. Friday. \"Next Week.\"", parts=[["Thursday.", "come up on Thursday"], ["Friday.", "But then tomorrow comes"], ["\"Next Week.\"", "start again next week"]]),
 dict(id="G17", kind="lt", start="There is no decision", end="working out or not", tail=0.5, topic="KEY POINT",
      point="Daily Means NO Decision To Make.", parts=[["Daily Means NO Decision To Make.", "There is no decision"]]),
 dict(id="G18", kind="lt", start="You don't have to do an hour", end="no matter what happens", topic="START SMALL",
      point="5 Minutes A Day Builds The HABIT.", parts=[["5 Minutes A Day", "Just start with five minutes"], ["Builds The HABIT.", "get in that habit"]]),
 # ---------------- reason 3
 dict(id="G19", kind="lt", start="Here's the third reason", end="a few times per week", topic="REASON 3 OF 4",
      point="You Can Train In The MORNING.", parts=[["You Can Train In The MORNING.", "Here's the third reason"]]),
 dict(id="G20", kind="lt", start="You're gonna lift more", end="Everything gets better", topic="MORNING WORKOUTS",
      point="Lift More. Feel Better. Eat Better.", parts=[["Lift More.", "You're gonna lift more"], ["Feel Better.", "feel so much better"], ["Eat Better.", "better eating decisions"]]),
 dict(id="G21", kind="lt", start="if you are working out five minutes", end="work out in the morning", tail=0.6, topic="KEY POINT",
      point="5 Minutes Fits ANY Morning.", parts=[["5 Minutes Fits ANY Morning.", "five minutes on the other hand"]]),
 # ---------------- reason 4
 dict(id="G22", kind="lt", start="the final reason why", end="times per week", topic="REASON 4 OF 4",
      point="It Becomes WHO YOU ARE.", parts=[["It Becomes WHO YOU ARE.", "the final reason why"]]),
 dict(id="C13", kind="clip", start="It's kind of like brushing your teeth", end="let your teeth rot", tail=0.2, src=["/Volumes/Extreme/_edit_work/ro07/stock/teeth.mp4@1.0"], people="other", physique=False, 
      note="new stock, Pexels 6322934: a man brushes his teeth at a bathroom mirror"),
 dict(id="G23", kind="lt", start="Once you are working out every day", end="that's who you are", tail=0.6, topic="KEY POINT",
      point="Make It As Automatic As BRUSHING YOUR TEETH.", parts=[["Make It As Automatic", "Once you are working out"], ["As BRUSHING YOUR TEETH.", "just like brushing"]]),
 # ---------------- when to work out
 dict(id="G24", kind="lt", start="the absolute best time to do this", end="then you can do this", topic="BEST TIME TO WORK OUT",
      point="The MORNING.", parts=[["The MORNING.", "is the morning"]]),
 dict(id="C14", kind="clip", start="you can wake up 20 minutes earlier", end="five minute workout in", tail=0.2, src=["B0334@2.0"], people="other", physique=False,
      note="library stock: a man wakes up and stretches in bed"),
 dict(id="G25", kind="lt", start="The second best time to work out", end="then come back", topic="SECOND BEST TIME",
      point="Right After Work. Don't Go Home First.", parts=[["Right After Work.", "immediately after work"], ["Don't Go Home First.", "if you go home"]]),
 dict(id="C16", kind="clip", start="You need to go straight from your job", end="home workout area", tail=0.1, src=["B0141@2.0"], people="other", physique=False,
      note="library stock: a man walks past a row of treadmills in a gym"),
 dict(id="G26", kind="lt", start="The absolute worst time", end="until late at night", topic="WORST TIME",
      point="Late At NIGHT.", parts=[["Late At NIGHT.", "late at night"]]),
 dict(id="C17", kind="clip", start="it's gonna disrupt your sleep", end="gain more fat", tail=0.2, src=["B0354@6.0"], people="other", physique=False,
      note="library stock: a man lies awake at night, tossing and turning"),
 dict(id="G27", kind="lt", start="don't work out at night", end="right after work", tail=0.8, topic="WHEN TO WORK OUT",
      point="NEVER At Night. Morning First. After Work Second.", parts=[["NEVER At Night.", "don't work out at night"], ["Morning First.", "work out in the morning"], ["After Work Second.", "second best choice"]]),
 # ---------------- the plan, month by month
 dict(id="G28", kind="lt", start="I recommend just doing", end="at home every day", tail=0.8, topic="MONTH 1",
      point="5 Minutes. Bodyweight. At HOME.", parts=[["5 Minutes.", "short 5 minute"], ["Bodyweight.", "bodyweight workout"], ["At HOME.", "at home"]]),
 dict(id="F01", kind="scene", scene="fact", people="none", physique=False, start="If you're doing a five minute workout", end="five minute time commitment", tail=0.3, photo="/Volumes/Extreme/_edit_work/ro07/assets/traffic.png",
      eyebrow=["5 MIN GYM WORKOUT", "If you're doing a five"], headline=[["45 min", "45 minute"]],
      detail=["With the drive there and back.", "time commitment"], push=1.05, drift=-8),
 dict(id="G29", kind="lt", start="the next month, what I recommend", end="about to show you", topic="MONTH 2",
      point="Step Up To 10 Minutes.", parts=[["Step Up To 10 Minutes.", "10-minute workout"]]),
 dict(id="C18", kind="clip", start="is a kettlebell", end="examples of all this right now", tail=0.1, src=["B0431@1.0", "B0455@1.0", "B0436@2.0", "B0448@4.0", "B0452@0.5"], **DAN,
      note="Dan's own library B-roll, one piece of equipment each, in the order he lists them: kettlebell, yoga mat, ab wheel, jump rope, push-up handles"),
 dict(id="G30", kind="lt", start="I'll link in the description", end="up to the next level", topic="LINKS IN THE DESCRIPTION",
      point="The Basic Equipment I Use Is LINKED Below.", parts=[["The Basic Equipment I Use Is LINKED Below.", "link in the description"]]),
 dict(id="G31", kind="lt", start="Third month", end="same basic equipment", tail=0.8, topic="MONTH 3",
      point="15 Minutes. Same Equipment.", parts=[["15 Minutes.", "15 minute workouts"], ["Same Equipment.", "same basic equipment"]]),
 dict(id="G32", kind="lt", start="At the fourth month", end="commercial gym", tail=0.5, topic="MONTH 4",
      point="A Home Gym Or A Gym MEMBERSHIP.", parts=[["A Home Gym", "home gym setup"], ["Or A Gym MEMBERSHIP.", "commercial gym"]]),
 dict(id="C19", kind="clip", start="it's worth the investment", end="work out at home", tail=0.1, src=["B0327@1.0"], people="other", physique=False,
      note="library stock: a man slides a plate onto a barbell at a squat rack"),
 dict(id="G33", kind="lt", start="just keep stepping your workouts", end="easily and naturally", topic="AFTER THAT",
      point="Add 5 Minutes: 3 More SETS.", parts=[["Add 5 Minutes:", "another five minutes"], ["3 More SETS.", "three more sets"]]),
 dict(id="G34", kind="lt", start="keep stepping it up until", end="for you to get to", topic="THE LONG-TERM GOAL",
      point="1 Hour A Day. Give It 3 To 5 YEARS.", parts=[["1 Hour A Day.", "one hour per day"], ["Give It 3 To 5 YEARS.", "long-term goal"]]),
 dict(id="C20", kind="clip", start="every aspect of your life is going to change", end="different for you", tail=0.1, src=[br("C1490", 15.6), br("C1490", 45.8)], grade="C1490", **DAN,
      note="Dan's B-roll from this shoot: front and side poses by the pool (real moving footage, so no photo label)"),
 # ---------------- the workout
 dict(id="G35", kind="lt", start="When you're first starting working out", end="without proper form", topic="THE 5-MINUTE BEGINNER WORKOUT",
      point="Time Your Sets. Don't Count REPS.", parts=[["Time Your Sets.", "When you're first"], ["Don't Count REPS.", "counting reps"]]),
 dict(id="G36", kind="lt", start="The one I personally use", end="great workout timer", topic="FREE WORKOUT TIMER APP",
      point="GYMBOSS Interval Timer.", parts=[["GYMBOSS Interval Timer.", "Gymboss"]]),
 dict(id="G37", kind="lt", start="do five 30", end="four times", tail=0.8, topic="SET YOUR TIMER",
      point="5 Rounds x 30 Seconds. Repeat 4 Times.", parts=[["5 Rounds x 30 Seconds.", "do five 30"], ["Repeat 4 Times.", "repeat those rounds"]]),
 dict(id="G38", kind="lt", start="The first round is going to be", end="shoulder width apart", topic="ROUND 1 OF 5: 30 SECONDS",
      point="Bodyweight SQUATS.", parts=[["Bodyweight SQUATS.", "bodyweight squats"]]),
 dict(id="C21", kind="clip", start="make sure your weight is on your heels", end="back up for 30 seconds", tail=0.15, src=[br("C1490", 78.0)], grade="C1490", **DAN,
      note="Dan's B-roll from this shoot: bodyweight squats, shown for the whole run of form cues"),
 dict(id="G39", kind="lt", start="next you're gonna do 30 seconds of push", end="for beginners", topic="ROUND 2 OF 5: 30 SECONDS",
      point="PUSH-UPS.", parts=[["PUSH-UPS.", "push-ups"]]),
 dict(id="C22", kind="clip", start="You're going to lower yourself down slowly", end="then go back up", tail=0.1, src=[br("C1491", 12.5)], grade="C1491", **DAN,
      note="Dan's B-roll from this shoot: push-ups on the mat, no handles (the version he is teaching)"),
 dict(id="C23", kind="clip", start="So make sure to keep your body flat", end="controlled the entire time", tail=0.1, src=[br("C1491", 1.0)], grade="C1491", **DAN,
      note="Dan's B-roll from this shoot: more of the same push-up take (other reps)"),
 dict(id="C24", kind="clip", start="then you can put your knees on the ground", end="knees position", tail=0.2, src=["A0093@2.0"], label="AI-GENERATED", people="dan", physique=False,
      note="library AI demo from the app: AI Dan doing knee push-ups (no real footage of the knee version exists)"),
 dict(id="G40", kind="lt", start="you're going to do 30 seconds of lunges", end="30 seconds of lunges", tail=1.6, topic="ROUND 3 OF 5: 30 SECONDS",
      point="LUNGES.", parts=[["LUNGES.", "lunges"]]),
 dict(id="C25", kind="clip", start="take a big step forward", end="spike your knee on the ground", tail=0.1, src=[br("C1493", 19.0)], grade="C1493", **DAN,
      note="Dan's B-roll from this shoot: walking lunges on the yoga mat"),
 dict(id="G41", kind="lt", start="Finally, we have our towel row", end="learning it from him", topic="ROUND 4 OF 5: 30 SECONDS",
      point="TOWEL ROWS.", parts=[["TOWEL ROWS.", "towel row"]]),
 dict(id="C26", kind="clip", start="you're going to hold your towel", end="as you can on the towel", tail=0.1, src=[br("C1494", 16.0)], grade="C1494", **DAN,
      note="Dan's B-roll from this shoot: towel rows, side on"),
 dict(id="C27", kind="clip", start="A good trick you can use", end="then you're doing it right", tail=0.1, src=[br("C1494", 68.0)], grade="C1494", people="dan", physique=False,
      note="Dan's B-roll from this shoot: the karate chop test on the towel (limp first, then tight)"),
 dict(id="C28", kind="clip", start="slowly with control, roll it back", end="extend your arms again", tail=0.1, src=[br("C1493", 70.0)], grade="C1493", **DAN,
      note="Dan's B-roll from this shoot: towel rows, front on"),
 dict(id="G42", kind="lt", start="after that you have 30 seconds of rest", end="active recovery", tail=0.8, topic="ROUND 5 OF 5: 30 SECONDS",
      point="REST. Jog In Place.", parts=[["REST.", "30 seconds of rest"], ["Jog In Place.", "jog in place"]]),
 dict(id="G43", kind="lt", start="go through the entire circuit twice", end="three or four times", tail=0.8, topic="HOW MANY CIRCUITS?",
      point="Beginner: 2 = 5 Minutes. Advanced: 3 Or 4.", parts=[["Beginner: 2 = 5 Minutes.", "circuit twice"], ["Advanced: 3 Or 4.", "little bit more advanced"]]),
 dict(id="G44", kind="lt", start="it's better to do something short", end="long inconsistently", tail=0.8, topic="KEY POINT",
      point="Short And DAILY Beats Long And Inconsistent.", parts=[["Short And DAILY", "something short every day"], ["Beats Long And Inconsistent.", "something long"]]),
 # ---------------- outro
 dict(id="P01", kind="clip", start="you can generate an image of your future self", end="six-pack abs", tail=0.2, src=[f"{RO6}/round5/phone/P01-softblue.mp4@0.0"], people="dan", physique=True, label="AI-GENERATED", label_in_picture=True,
      note="the approved self-generation demo (sunglasses photo to pool goal) in the Soft Blue phone card, the same file as RO-06"),
 dict(id="G45", kind="lt", start="we also have an AI macro tracker", end="body that you want", tail=0.4, topic="ALSO IN THE APP",
      point="AI Macro Tracker. AI Nutritionist. AI Trainer.", parts=[["AI Macro Tracker.", "macro tracker"], ["AI Nutritionist.", "nutritionist"], ["AI Trainer.", "personal trainer"]]),
]
